### ISSUE TITLE
v2.2.0 useSlots Type resolution failure

### ISSUE THREAD

**Issue by SevenJoker** [vuejs/language-tools#5116]
### Vue - Official extension or vue-tsc version

2.2.0

### VSCode version

1.96.1

### Vue version

3.4.21

### TypeScript version

use jsdoc

### Steps to reproduce

![image](https://github.com/user-attachments/assets/511d960f-6385-406c-950c-8b877c4ba487)

### What is expected?

![image](https://github.com/user-attachments/assets/846c1b39-2e25-4271-ae61-0d083d8410ba)

### What is actually happening?

useSlots result type is any
rollback version to 2.1.10 is normal
![image](https://github.com/user-attachments/assets/02d419c0-1038-4952-817d-472cec7a8fbe)

**Comment by KazariEX** [comment]
How do you use `slots` in the template?

**Comment by KazariEX** [comment]
See https://github.com/vuejs/language-tools/pull/5055#issuecomment-2575050699

If you want to get an `slots` object without type inference and use it in the template, it would be better to use `const slots = defineSlots()` to skip type resolution.

**Comment by realByg** [comment]
> Usage of slots and attrs inside <script setup> should be relatively rare, since you can access them directly as $slots and $attrs in the template.

https://vuejs.org/api/sfc-script-setup#useslots-useattrs

**Comment by KazariEX** [comment]
Just a `defineSlots()`, no need to use its return value, you can continue to use `$slots` in the template.

https://vuejs-language-tools.vercel.app/zh/features/slots

**Comment by brc-dd** [comment]
`$slots` in template is also not behaving correctly 👀 

Example:

```vue
<script lang="ts">
export default { inheritAttrs: false }
</script>

<script setup lang="ts">
defineProps<{ is?: any }>()
</script>

<template>
  <component v-if="is" :is="is" v-bind="$attrs">
    <template v-for="(_, slot) of $slots" #[slot]="scope">
      <slot :name="slot" v-bind="scope" />
    </template>
  </component>
  <slot v-else />
</template>
```

Here type of `slot` should be `string | number`. But with `vue-tsc@~2.2`, it throws:

```
lib/components/SFragment.vue:11:26 - error TS7022: 'slot' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.

11     <template v-for="(_, slot) of $slots" #[slot]="scope">
                            ~~~~
```

It was working fine with `vue-tsc@~2.1`

**Comment by KazariEX** [comment]
See https://vuejs-language-tools.vercel.app/features/slots#how-to-handle-indeterminate-slot-types

**Comment by stephane303** [comment]
This prevents me to upgrade to v2.2.0, I would simply like to ignore this error, so that my CI keeps working.

**Comment by stephane303** [comment]
You cam use   to get rid of the error
