### ISSUE TITLE
Error TS2339 after upgrade from 1.8.8 to 1.8.15

### ISSUE THREAD

**Issue by swiergot** [vuejs/language-tools#3613]
After the following upgrades:

- vue/typescript 1.8.8 -> 1.8.15
- vue/language-core 1.8.8 -> 1.8.15
- vue-tsc 1.8.8 to 1.8.15

I get a lot of errors:

`error TS2339: Property 'XXX' does not exist on type '{ $: ComponentInternalInstance; $data: {}; $props: { key?: string | number | symbol | undefined; class?: unknown; ref?: VNodeRef | undefined; ref_for?: boolean | undefined; ... 7 more ...; style?: unknown; }; ... 10 more ...; $watch<T extends string | ((...args: any) => any)>(source: T, cb: T extends (...args: any) ...'.`

where XXX is a property, a method or a computed property. The errors are in templates. The script part has no errors.

That is happening only to some  of my components, while the other are fine. Sadly I cannot spot any difference, they are basically similar. I've been staring at the code for hours.

Any clues?

Thanks.

**Comment by so1ve** [comment]
Duplicate of #3598

**Comment by so1ve** [comment]
You are using `script setup` and `script` together, and the property comes from `script` right

**Comment by swiergot** [comment]
Oh, indeed that's the difference...

Thanks so much. I assume it's not wrong to do so?

What I have in `script setup` are imports of other components. If I move the imports to `script`, I also have to use the `components` property, otherwise the code compiles but components do not resolve in runtime.

**Comment by so1ve** [comment]
Yup, your usage is valid and volar should support it. This is a regression due to an internal refactor that doesn't merge those two blocks correctly.

**Comment by swiergot** [comment]
Got it, thanks again!
