### ISSUE TITLE
`ts(2307)` error keeps showing in the vscode diff editor's left-side (after upgraded to 1.1.x)

### ISSUE THREAD

**Issue by ecoms-ye** [vuejs/language-tools#2391]
## Environment

- Vue: 2.7.14 (from `npm create vue@2`)
- Volar: 1.1.0 & 1.1.1
- vscode: 1.75.1
- WSL2 (ubuntu 22.04)

## Description

```
Cannot find module 'vue' or its corresponding type declarations.ts(2307)
```

![image](https://user-images.githubusercontent.com/117143128/219271685-e3aaac52-fcf5-4c17-84a3-b6519f5dfacc.png)

After upgraded to 1.1.x, `import` in `.vue` file would show this `ts(2307)` error in vscode's "Source Control" diff editor.

## Expectation

Do not show `ts(2307)` error in the diff editor if there is no error.

Just like #2389, I think it's another display bug because the same code right-side works as usual.
