### ISSUE TITLE
Regression vue-tsc v1.6.1 -> v1.6.2+

### ISSUE THREAD

**Issue by Shinigami92** [vuejs/language-tools#3108]
I could not identify yet what the issue is, but when I update from vue-tsc v1.6.1 to v1.6.2 or v1.6.3 we get some TS errors in our project.

I will try to isolate them and find out what it is. So right now this issue is just for awareness that something broke and we are now "stuck" on v1.6.1 in our project (pinned the version).

**Comment by dargmuesli** [comment]
Example build log after update: https://github.com/dargmuesli/creal/actions/runs/4859912783/jobs/8663118168?pr=304#step:7:1505

**Comment by Shinigami92** [comment]
This is our current CI

<details>
<summary>Build Log</summary>

```node
> pnpm install
 WARN  deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
Packages: +10 -3
++++++++++---
Progress: resolved 504, reused 483, downloaded 0, added 10, done

devDependencies:
- vue-tsc 1.6.1
+ vue-tsc 1.6.3

Done in 9.3s
> pnpm run build

> frontend@0.0.8 build /projectpath/frontend
> vue-tsc --noEmit && vite build

src/pages/AlarmsPage.vue:122:7 - error TS2322: Type 'Ref<({ title?: TableColumnGroupTitle | undefined; type?: undefined; key: ColumnKey; children: { title?: TableColumnTitle | undefined; ... 31 more ...; cellProps?: ((rowData: RowData, rowIndex: number) => HTMLAttributes) | undefined; }[]; ... 9 more ...; cellProps?: ((rowData: RowData, rowIndex: number) => HTMLAttrib...' is not assignable to type 'Ref<TableColumns<RowData>>'.
  Type '({ title?: TableColumnGroupTitle | undefined; type?: undefined; key: ColumnKey; children: { title?: TableColumnTitle | undefined; ... 31 more ...; cellProps?: ((rowData: RowData, rowIndex: number) => HTMLAttributes) | undefined; }[]; ... 9 more ...; cellProps?: ((rowData: RowData, rowIndex: number) => HTMLAttributes...' is not assignable to type 'TableColumns<RowData>'.
    Type '{ title?: TableColumnGroupTitle | undefined; type?: undefined; key: ColumnKey; children: { title?: TableColumnTitle | undefined; ... 31 more ...; cellProps?: ((rowData: RowData, rowIndex: number) => HTMLAttributes) | undefined; }[]; ... 9 more ...; cellProps?: ((rowData: RowData, rowIndex: number) => HTMLAttributes)...' is not assignable to type 'TableColumn<RowData>'.
      Type '{ title?: TableColumnGroupTitle | undefined; type?: undefined; key: ColumnKey; children: { title?: TableColumnTitle | undefined; ... 31 more ...; cellProps?: ((rowData: RowData, rowIndex: number) => HTMLAttributes) | undefined; }[]; ... 9 more ...; cellProps?: ((rowData: RowData, rowIndex: number) => HTMLAttributes)...' is not assignable to type 'TableColumn<RowData>'.
        Type '{ title?: TableColumnGroupTitle | undefined; type?: undefined; key: ColumnKey; children: { title?: TableColumnTitle | undefined; ... 31 more ...; cellProps?: ((rowData: RowData, rowIndex: number) => HTMLAttributes) | undefined; }[]; ... 9 more ...; cellProps?: ((rowData: RowData, rowIndex: number) => HTMLAttributes)...' is not assignable to type 'TableColumnGroup<RowData>'.
          Type '{ title?: TableColumnGroupTitle | undefined; type?: undefined; key: ColumnKey; children: { title?: TableColumnTitle | undefined; ... 31 more ...; cellProps?: ((rowData: RowData, rowIndex: number) => HTMLAttributes) | undefined; }[]; ... 9 more ...; cellProps?: ((rowData: RowData, rowIndex: number) => HTMLAttributes)...' is not assignable to type '{ title?: TableColumnGroupTitle | undefined; type?: undefined; key: ColumnKey; children: TableBaseColumn<RowData>[]; resizable?: boolean | undefined; filterOptions?: undefined; }'.
            Types of property 'children' are incompatible.
              Type '{ title?: TableColumnTitle | undefined; titleColSpan?: number | undefined; type?: undefined; key: ColumnKey; tree?: boolean | undefined; sorter?: boolean | "default" | CompareFn<...> | { ...; } | undefined; ... 26 more ...; cellProps?: ((rowData: RowData, rowIndex: number) => HTMLAttributes) | undefined; }[]' is not assignable to type 'TableBaseColumn<RowData>[]'.
                Type '{ title?: TableColumnTitle | undefined; titleColSpan?: number | undefined; type?: undefined; key: ColumnKey; tree?: boolean | undefined; sorter?: boolean | "default" | CompareFn<...> | { ...; } | undefined; ... 26 more ...; cellProps?: ((rowData: RowData, rowIndex: number) => HTMLAttributes) | undefined; }' is not assignable to type 'TableBaseColumn<RowData>'.
                  Type '{ title?: TableColumnTitle | undefined; titleColSpan?: number | undefined; type?: undefined; key: ColumnKey; tree?: boolean | undefined; sorter?: boolean | "default" | CompareFn<...> | { ...; } | undefined; ... 26 more ...; cellProps?: ((rowData: RowData, rowIndex: number) => HTMLAttributes) | undefined; }' is not assignable to type 'CommonColumnInfo<RowData>'.
                    Types of property 'ellipsis' are incompatible.
                      Type 'boolean | { themeOverrides?: { peers?: { Tooltip?: { borderRadius?: string | undefined; boxShadow?: string | undefined; color?: string | undefined; textColor?: string | undefined; padding?: string | undefined; peers?: { ...; } | undefined; common?: { ...; } | undefined; } | undefined; } | undefined; common?: { ...; ...' is not assignable to type 'Ellipsis | undefined'.

122 const columns: Ref<DataTableColumns<RowData>> = ref<DataTableColumns<RowData>>([
          ~~~~~~~

src/pages/EquipmentsPage.vue:138:7 - error TS2322: Type 'Ref<({ title?: TableColumnGroupTitle | undefined; type?: undefined; key: ColumnKey; children: { title?: TableColumnTitle | undefined; ... 31 more ...; cellProps?: ((rowData: RowData, rowIndex: number) => HTMLAttributes) | undefined; }[]; ... 9 more ...; cellProps?: ((rowData: RowData, rowIndex: number) => HTMLAttrib...' is not assignable to type 'Ref<TableColumns<RowData>>'.
  Type '({ title?: TableColumnGroupTitle | undefined; type?: undefined; key: ColumnKey; children: { title?: TableColumnTitle | undefined; ... 31 more ...; cellProps?: ((rowData: RowData, rowIndex: number) => HTMLAttributes) | undefined; }[]; ... 9 more ...; cellProps?: ((rowData: RowData, rowIndex: number) => HTMLAttributes...' is not assignable to type 'TableColumns<RowData>'.
    Type '{ title?: TableColumnGroupTitle | undefined; type?: undefined; key: ColumnKey; children: { title?: TableColumnTitle | undefined; ... 31 more ...; cellProps?: ((rowData: RowData, rowIndex: number) => HTMLAttributes) | undefined; }[]; ... 9 more ...; cellProps?: ((rowData: RowData, rowIndex: number) => HTMLAttributes)...' is not assignable to type 'TableColumn<RowData>'.
      Type '{ title?: TableColumnGroupTitle | undefined; type?: undefined; key: ColumnKey; children: { title?: TableColumnTitle | undefined; ... 31 more ...; cellProps?: ((rowData: RowData, rowIndex: number) => HTMLAttributes) | undefined; }[]; ... 9 more ...; cellProps?: ((rowData: RowData, rowIndex: number) => HTMLAttributes)...' is not assignable to type 'TableColumn<RowData>'.
        Type '{ title?: TableColumnGroupTitle | undefined; type?: undefined; key: ColumnKey; children: { title?: TableColumnTitle | undefined; ... 31 more ...; cellProps?: ((rowData: RowData, rowIndex: number) => HTMLAttributes) | undefined; }[]; ... 9 more ...; cellProps?: ((rowData: RowData, rowIndex: number) => HTMLAttributes)...' is not assignable to type 'TableColumnGroup<RowData>'.
          Type '{ title?: TableColumnGroupTitle | undefined; type?: undefined; key: ColumnKey; children: { title?: TableColumnTitle | undefined; ... 31 more ...; cellProps?: ((rowData: RowData, rowIndex: number) => HTMLAttributes) | undefined; }[]; ... 9 more ...; cellProps?: ((rowData: RowData, rowIndex: number) => HTMLAttributes)...' is not assignable to type '{ title?: TableColumnGroupTitle | undefined; type?: undefined; key: ColumnKey; children: TableBaseColumn<RowData>[]; resizable?: boolean | undefined; filterOptions?: undefined; }'.
            Types of property 'children' are incompatible.
              Type '{ title?: TableColumnTitle | undefined; titleColSpan?: number | undefined; type?: undefined; key: ColumnKey; tree?: boolean | undefined; sorter?: boolean | "default" | CompareFn<...> | { ...; } | undefined; ... 26 more ...; cellProps?: ((rowData: RowData, rowIndex: number) => HTMLAttributes) | undefined; }[]' is not assignable to type 'TableBaseColumn<RowData>[]'.
                Type '{ title?: TableColumnTitle | undefined; titleColSpan?: number | undefined; type?: undefined; key: ColumnKey; tree?: boolean | undefined; sorter?: boolean | "default" | CompareFn<...> | { ...; } | undefined; ... 26 more ...; cellProps?: ((rowData: RowData, rowIndex: number) => HTMLAttributes) | undefined; }' is not assignable to type 'TableBaseColumn<RowData>'.
                  Type '{ title?: TableColumnTitle | undefined; titleColSpan?: number | undefined; type?: undefined; key: ColumnKey; tree?: boolean | undefined; sorter?: boolean | "default" | CompareFn<...> | { ...; } | undefined; ... 26 more ...; cellProps?: ((rowData: RowData, rowIndex: number) => HTMLAttributes) | undefined; }' is not assignable to type 'CommonColumnInfo<RowData>'.
                    Types of property 'ellipsis' are incompatible.
                      Type 'boolean | { themeOverrides?: { peers?: { Tooltip?: { borderRadius?: string | undefined; boxShadow?: string | undefined; color?: string | undefined; textColor?: string | undefined; padding?: string | undefined; peers?: { ...; } | undefined; common?: { ...; } | undefined; } | undefined; } | undefined; common?: { ...; ...' is not assignable to type 'Ellipsis | undefined'.

138 const columns: Ref<DataTableColumns<RowData>> = ref<DataTableColumns<RowData>>([
          ~~~~~~~

src/components/molecules/DCaptureFace.vue:137:24 - error TS2345: Argument of type '{ disablePictureInPicture: boolean; height: number; onenterpictureinpicture: ((this: HTMLVideoElement, ev: Event) => any) | null; onleavepictureinpicture: ((this: HTMLVideoElement, ev: Event) => any) | null; ... 347 more ...; focus: (options?: FocusOptions | undefined) => void; }' is not assignable to parameter of type 'CanvasImageSource'.
  Type '{ disablePictureInPicture: boolean; height: number; onenterpictureinpicture: ((this: HTMLVideoElement, ev: Event) => any) | null; onleavepictureinpicture: ((this: HTMLVideoElement, ev: Event) => any) | null; ... 347 more ...; focus: (options?: FocusOptions | undefined) => void; }' is not assignable to type 'HTMLVideoElement'.
    Types of property 'offsetParent' are incompatible.
      Type '{ readonly attributes: { [x: number]: { readonly localName: string; readonly name: string; readonly namespaceURI: string | null; readonly ownerDocument: { readonly URL: string; alinkColor: string; readonly all: { [x: number]: ...; readonly length: number; item: (nameOrIndex?: string | undefined) => Element | ... 1 m...' is not assignable to type 'Element | null'.
        Type '{ readonly attributes: { [x: number]: { readonly localName: string; readonly name: string; readonly namespaceURI: string | null; readonly ownerDocument: { readonly URL: string; alinkColor: string; readonly all: { [x: number]: ...; readonly length: number; item: (nameOrIndex?: string | undefined) => Element | ... 1 m...' is not assignable to type 'Element'.
          Types of property 'attributes' are incompatible.
            Type '{ [x: number]: { readonly localName: string; readonly name: string; readonly namespaceURI: string | null; readonly ownerDocument: { readonly URL: string; alinkColor: string; readonly all: { [x: number]: { readonly attributes: ...; ... 165 more ...; readonly assignedSlot: { ...; } | null; }; readonly length: number; ...' is not assignable to type 'NamedNodeMap'.
              'number' index signatures are incompatible.
                Type '{ readonly localName: string; readonly name: string; readonly namespaceURI: string | null; readonly ownerDocument: { readonly URL: string; alinkColor: string; readonly all: { [x: number]: { readonly attributes: { [x: number]: ...; ... 8 more ...; [Symbol.iterator]: () => IterableIterator<...>; }; ... 165 more ...; r...' is not assignable to type 'Attr'.
                  The types of 'ownerDocument.anchors' are incompatible between these types.
                    Type '{ [x: number]: { charset: string; coords: string; download: string; hreflang: string; name: string; ping: string; referrerPolicy: string; rel: string; readonly relList: { [x: number]: string; readonly length: number; ... 13 more ...; [Symbol.iterator]: () => IterableIterator<...>; }; ... 308 more ...; username: stri...' is not assignable to type 'HTMLCollectionOf<HTMLAnchorElement>'.
                      'number' index signatures are incompatible.
                        Type '{ charset: string; coords: string; download: string; hreflang: string; name: string; ping: string; referrerPolicy: string; rel: string; readonly relList: { [x: number]: string; readonly length: number; value: string; ... 12 more ...; [Symbol.iterator]: () => IterableIterator<...>; }; ... 308 more ...; username: stri...' is not assignable to type 'HTMLAnchorElement'.
                          Types of property 'shadowRoot' are incompatible.
                            Type '{ readonly delegatesFocus: boolean; readonly host: { readonly attributes: { [x: number]: { readonly localName: string; readonly name: string; readonly namespaceURI: string | null; readonly ownerDocument: { readonly URL: string; ... 256 more ...; evaluate: (expression: string, contextNode: Node, resolver?: XPathNSRes...' is not assignable to type 'ShadowRoot | null'.
                              Type '{ readonly delegatesFocus: boolean; readonly host: { readonly attributes: { [x: number]: { readonly localName: string; readonly name: string; readonly namespaceURI: string | null; readonly ownerDocument: { readonly URL: string; ... 256 more ...; evaluate: (expression: string, contextNode: Node, resolver?: XPathNSRes...' is not assignable to type 'ShadowRoot'.
                                Types of property 'childNodes' are incompatible.
                                  Type '{ [x: number]: { after: (...nodes: (string | Node)[]) => void; before: (...nodes: (string | Node)[]) => void; remove: () => void; replaceWith: (...nodes: (string | Node)[]) => void; readonly baseURI: string; ... 48 more ...; removeEventListener: (type: string, callback: EventListenerOrEventListenerObject | null, opt...' is not assignable to type 'NodeListOf<ChildNode>'.
                                    'number' index signatures are incompatible.
                                      Type '{ after: (...nodes: (string | Node)[]) => void; before: (...nodes: (string | Node)[]) => void; remove: () => void; replaceWith: (...nodes: (string | Node)[]) => void; readonly baseURI: string; ... 48 more ...; removeEventListener: (type: string, callback: EventListenerOrEventListenerObject | null, options?: boolean ...' is not assignable to type 'ChildNode'.
                                        Types of property 'parentElement' are incompatible.
                                          Type '{ accessKey: string; readonly accessKeyLabel: string; autocapitalize: string; dir: string; draggable: boolean; hidden: boolean; inert: boolean; innerText: string; lang: string; readonly offsetHeight: number; ... 281 more ...; focus: (options?: FocusOptions | undefined) => void; } | null' is not assignable to type 'HTMLElement | null'.
                                            Type '{ accessKey: string; readonly accessKeyLabel: string; autocapitalize: string; dir: string; draggable: boolean; hidden: boolean; inert: boolean; innerText: string; lang: string; readonly offsetHeight: number; ... 281 more ...; focus: (options?: FocusOptions | undefined) => void; }' is not assignable to type 'HTMLElement'.
                                              Types of property 'assignedSlot' are incompatible.
                                                Type '{ name: string; assign: (...nodes: (Element | Text)[]) => void; assignedElements: (options?: AssignedNodesOptions | undefined) => Element[]; ... 292 more ...; focus: (options?: FocusOptions | undefined) => void; } | null' is not assignable to type 'HTMLSlotElement | null'.
                                                  Type '{ name: string; assign: (...nodes: (Element | Text)[]) => void; assignedElements: (options?: AssignedNodesOptions | undefined) => Element[]; ... 292 more ...; focus: (options?: FocusOptions | undefined) => void; }' is not assignable to type 'HTMLSlotElement'.
                                                    The types of 'style.parentRule' are incompatible between these types.
                                                      Type '{ cssText: string; readonly parentRule: ... | null; readonly parentStyleSheet: { readonly cssRules: { [x: number]: ...; readonly length: number; item: (index: number) => CSSRule | null; [Symbol.iterator]: () => IterableIterator<...>; }; ... 14 more ...; readonly type: string; } | null; ... 10 more ...; readonly SUPP...' is not assignable to type 'CSSRule | null'.
                                                        Type '{ cssText: string; readonly parentRule: ... | null; readonly parentStyleSheet: { readonly cssRules: { [x: number]: ...; readonly length: number; item: (index: number) => CSSRule | null; [Symbol.iterator]: () => IterableIterator<...>; }; ... 14 more ...; readonly type: string; } | null; ... 10 more ...; readonly SUPP...' is not assignable to type 'CSSRule'.
                                                          Types of property 'parentStyleSheet' are incompatible.
                                                            Type '{ readonly cssRules: { [x: number]: { cssText: string; readonly parentRule: ... | null; readonly parentStyleSheet: ... | null; readonly type: number; readonly STYLE_RULE: 1; readonly CHARSET_RULE: 2; ... 7 more ...; readonly SUPPORTS_RULE: 12; }; readonly length: number; item: (index: number) => CSSRule | null; [Sym...' is not assignable to type 'CSSStyleSheet | null'.
                                                              Type '{ readonly cssRules: { [x: number]: { cssText: string; readonly parentRule: ... | null; readonly parentStyleSheet: ... | null; readonly type: number; readonly STYLE_RULE: 1; readonly CHARSET_RULE: 2; ... 7 more ...; readonly SUPPORTS_RULE: 12; }; readonly length: number; item: (index: number) => CSSRule | null; [Sym...' is not assignable to type 'CSSStyleSheet'.
                                                                Types of property 'ownerNode' are incompatible.
                                                                  Type '{ readonly attributes: { [x: number]: { readonly localName: string; readonly name: string; readonly namespaceURI: string | null; readonly ownerDocument: { readonly URL: string; alinkColor: string; readonly all: { [x: number]: ...; readonly length: number; item: (nameOrIndex?: string | undefined) => Element | ... 1 m...' is not assignable to type 'Element | ProcessingInstruction | null'.
                                                                    Type '{ readonly attributes: { [x: number]: { readonly localName: string; readonly name: string; readonly namespaceURI: string | null; readonly ownerDocument: { readonly URL: string; alinkColor: string; readonly all: { [x: number]: ...; readonly length: number; item: (nameOrIndex?: string | undefined) => Element | ... 1 m...' is not assignable to type 'Element | ProcessingInstruction | null'.

137   context2d?.drawImage(videoRef.value, 0, 0);
                           ~~~~~~~~~~~~~~

src/components/molecules/DCaptureFace.vue:177:33 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(element: HTMLImageElement, options?: Options<HTMLImageElement> | undefined): Cropper', gave the following error.
    Argument of type '{ align: string; alt: string; border: string; readonly complete: boolean; crossOrigin: string | null; readonly currentSrc: string; decoding: "auto" | "async" | "sync"; height: number; hspace: number; ... 308 more ...; focus: (options?: FocusOptions | undefined) => void; }' is not assignable to parameter of type 'HTMLImageElement'.
      Types of property 'offsetParent' are incompatible.
        Type '{ readonly attributes: { [x: number]: { readonly localName: string; readonly name: string; readonly namespaceURI: string | null; readonly ownerDocument: { readonly URL: string; alinkColor: string; readonly all: { [x: number]: ...; readonly length: number; item: (nameOrIndex?: string | undefined) => Element | ... 1 m...' is not assignable to type 'Element | null'.
  Overload 2 of 2, '(element: HTMLCanvasElement, options?: Options<HTMLCanvasElement> | undefined): Cropper', gave the following error.
    Argument of type '{ align: string; alt: string; border: string; readonly complete: boolean; crossOrigin: string | null; readonly currentSrc: string; decoding: "auto" | "async" | "sync"; height: number; hspace: number; ... 308 more ...; focus: (options?: FocusOptions | undefined) => void; }' is not assignable to parameter of type 'HTMLCanvasElement'.
      Type '{ align: string; alt: string; border: string; readonly complete: boolean; crossOrigin: string | null; readonly currentSrc: string; decoding: "auto" | "async" | "sync"; height: number; hspace: number; ... 308 more ...; focus: (options?: FocusOptions | undefined) => void; }' is missing the following properties from type 'HTMLCanvasElement': captureStream, getContext, toBlob, toDataURL, transferControlToOffscreen

177     cropper.value = new Cropper(img, { aspectRatio: 7 / 9 });
                                    ~~~


src/pages/PersonsPage.vue:185:7 - error TS2322: Type 'Ref<({ title?: TableColumnGroupTitle | undefined; type?: undefined; key: ColumnKey; children: { title?: TableColumnTitle | undefined; ... 31 more ...; cellProps?: ((rowData: RowData, rowIndex: number) => HTMLAttributes) | undefined; }[]; ... 9 more ...; cellProps?: ((rowData: RowData, rowIndex: number) => HTMLAttrib...' is not assignable to type 'Ref<TableColumns<RowData>>'.
  Type '({ title?: TableColumnGroupTitle | undefined; type?: undefined; key: ColumnKey; children: { title?: TableColumnTitle | undefined; ... 31 more ...; cellProps?: ((rowData: RowData, rowIndex: number) => HTMLAttributes) | undefined; }[]; ... 9 more ...; cellProps?: ((rowData: RowData, rowIndex: number) => HTMLAttributes...' is not assignable to type 'TableColumns<RowData>'.
    Type '{ title?: TableColumnGroupTitle | undefined; type?: undefined; key: ColumnKey; children: { title?: TableColumnTitle | undefined; ... 31 more ...; cellProps?: ((rowData: RowData, rowIndex: number) => HTMLAttributes) | undefined; }[]; ... 9 more ...; cellProps?: ((rowData: RowData, rowIndex: number) => HTMLAttributes)...' is not assignable to type 'TableColumn<RowData>'.
      Type '{ title?: TableColumnGroupTitle | undefined; type?: undefined; key: ColumnKey; children: { title?: TableColumnTitle | undefined; ... 31 more ...; cellProps?: ((rowData: RowData, rowIndex: number) => HTMLAttributes) | undefined; }[]; ... 9 more ...; cellProps?: ((rowData: RowData, rowIndex: number) => HTMLAttributes)...' is not assignable to type 'TableColumn<RowData>'.
        Type '{ title?: TableColumnGroupTitle | undefined; type?: undefined; key: ColumnKey; children: { title?: TableColumnTitle | undefined; ... 31 more ...; cellProps?: ((rowData: RowData, rowIndex: number) => HTMLAttributes) | undefined; }[]; ... 9 more ...; cellProps?: ((rowData: RowData, rowIndex: number) => HTMLAttributes)...' is not assignable to type 'TableColumnGroup<RowData>'.
          Type '{ title?: TableColumnGroupTitle | undefined; type?: undefined; key: ColumnKey; children: { title?: TableColumnTitle | undefined; ... 31 more ...; cellProps?: ((rowData: RowData, rowIndex: number) => HTMLAttributes) | undefined; }[]; ... 9 more ...; cellProps?: ((rowData: RowData, rowIndex: number) => HTMLAttributes)...' is not assignable to type '{ title?: TableColumnGroupTitle | undefined; type?: undefined; key: ColumnKey; children: TableBaseColumn<RowData>[]; resizable?: boolean | undefined; filterOptions?: undefined; }'.
            Types of property 'children' are incompatible.
              Type '{ title?: TableColumnTitle | undefined; titleColSpan?: number | undefined; type?: undefined; key: ColumnKey; tree?: boolean | undefined; sorter?: boolean | "default" | CompareFn<...> | { ...; } | undefined; ... 26 more ...; cellProps?: ((rowData: RowData, rowIndex: number) => HTMLAttributes) | undefined; }[]' is not assignable to type 'TableBaseColumn<RowData>[]'.
                Type '{ title?: TableColumnTitle | undefined; titleColSpan?: number | undefined; type?: undefined; key: ColumnKey; tree?: boolean | undefined; sorter?: boolean | "default" | CompareFn<...> | { ...; } | undefined; ... 26 more ...; cellProps?: ((rowData: RowData, rowIndex: number) => HTMLAttributes) | undefined; }' is not assignable to type 'TableBaseColumn<RowData>'.
                  Type '{ title?: TableColumnTitle | undefined; titleColSpan?: number | undefined; type?: undefined; key: ColumnKey; tree?: boolean | undefined; sorter?: boolean | "default" | CompareFn<...> | { ...; } | undefined; ... 26 more ...; cellProps?: ((rowData: RowData, rowIndex: number) => HTMLAttributes) | undefined; }' is not assignable to type 'CommonColumnInfo<RowData>'.
                    Types of property 'ellipsis' are incompatible.
                      Type 'boolean | { themeOverrides?: { peers?: { Tooltip?: { borderRadius?: string | undefined; boxShadow?: string | undefined; color?: string | undefined; textColor?: string | undefined; padding?: string | undefined; peers?: { ...; } | undefined; common?: { ...; } | undefined; } | undefined; } | undefined; common?: { ...; ...' is not assignable to type 'Ellipsis | undefined'.
                        Type '{ themeOverrides?: { peers?: { Tooltip?: { borderRadius?: string | undefined; boxShadow?: string | undefined; color?: string | undefined; textColor?: string | undefined; padding?: string | undefined; peers?: { ...; } | undefined; common?: { ...; } | undefined; } | undefined; } | undefined; common?: { ...; } | undefi...' is not assignable to type 'Ellipsis | undefined'.
                          Type '{ themeOverrides?: { peers?: { Tooltip?: { borderRadius?: string | undefined; boxShadow?: string | undefined; color?: string | undefined; textColor?: string | undefined; padding?: string | undefined; peers?: { ...; } | undefined; common?: { ...; } | undefined; } | undefined; } | undefined; common?: { ...; } | undefi...' is not assignable to type 'EllipsisProps & { style?: CSSProperties | undefined; }'.
                            Type '{ themeOverrides?: { peers?: { Tooltip?: { borderRadius?: string | undefined; boxShadow?: string | undefined; color?: string | undefined; textColor?: string | undefined; padding?: string | undefined; peers?: { ...; } | undefined; common?: { ...; } | undefined; } | undefined; } | undefined; common?: { ...; } | undefi...' is not assignable to type 'EllipsisProps'.
                              Types of property 'tooltip' are incompatible.
                                Type 'boolean | { show?: boolean | undefined; raw?: boolean | undefined; disabled?: boolean | undefined; width?: number | "trigger" | undefined; to?: string | boolean | { accessKey: string; ... 290 more ...; focus: (options?: FocusOptions | undefined) => void; } | undefined; ... 28 more ...; maxWidth?: number | undefined;...' is not assignable to type 'boolean | PopoverProps | undefined'.
                                  Type '{ show?: boolean | undefined; raw?: boolean | undefined; disabled?: boolean | undefined; width?: number | "trigger" | undefined; to?: string | boolean | { accessKey: string; readonly accessKeyLabel: string; ... 289 more ...; focus: (options?: FocusOptions | undefined) => void; } | undefined; ... 28 more ...; maxWidt...' is not assignable to type 'boolean | PopoverProps | undefined'.
                                    Type '{ show?: boolean | undefined; raw?: boolean | undefined; disabled?: boolean | undefined; width?: number | "trigger" | undefined; to?: string | boolean | { accessKey: string; readonly accessKeyLabel: string; ... 289 more ...; focus: (options?: FocusOptions | undefined) => void; } | undefined; ... 28 more ...; maxWidt...' is not assignable to type 'PopoverProps'.
                                      Types of property 'to' are incompatible.
                                        Type 'string | boolean | { accessKey: string; readonly accessKeyLabel: string; autocapitalize: string; dir: string; draggable: boolean; hidden: boolean; inert: boolean; innerText: string; lang: string; ... 282 more ...; focus: (options?: FocusOptions | undefined) => void; } | undefined' is not assignable to type 'string | boolean | HTMLElement | undefined'.
                                          Type '{ accessKey: string; readonly accessKeyLabel: string; autocapitalize: string; dir: string; draggable: boolean; hidden: boolean; inert: boolean; innerText: string; lang: string; readonly offsetHeight: number; ... 281 more ...; focus: (options?: FocusOptions | undefined) => void; }' is not assignable to type 'string | boolean | HTMLElement | undefined'.
                                            Type '{ accessKey: string; readonly accessKeyLabel: string; autocapitalize: string; dir: string; draggable: boolean; hidden: boolean; inert: boolean; innerText: string; lang: string; readonly offsetHeight: number; ... 281 more ...; focus: (options?: FocusOptions | undefined) => void; }' is not assignable to type 'HTMLElement'.

185 const columns: Ref<DataTableColumns<RowData>> = ref<DataTableColumns<RowData>>([
          ~~~~~~~


Found 5 errors in 4 files.

Errors  Files
     1  src/pages/AlarmsPage.vue:122
     1  src/pages/EquipmentsPage.vue:138
     2  src/components/molecules/DCaptureFace.vue:137
     1  src/pages/PersonsPage.vue:185
 ELIFECYCLE  Command failed with exit code 2.
```

</details>

This is with v1.6.3
v1.6.2 has far more errors 👀, so v1.6.3 seems to have already fixed some stuff.

Non of these are reported with v1.6.1

**Comment by lazysteff** [comment]
> Seems like iterating over `any[]` leads to `unknown` elements (`availableLocales` is `any[]`).
Same issue. Reverted to 1.6.1 as a workaround.
