### ISSUE TITLE
ERROR Cannot start nuxt:  Cannot find module 'vue-tsc/out/index'

### ISSUE THREAD

**Issue by Archetipo95** [vuejs/language-tools#3969]
`ERROR Cannot start nuxt: Cannot find module 'vue-tsc/out/index'` after upgrading to v2

I'm using Nuxt 3 latest with a monorepo config (nuxt layers)

The only solution currently is to downgrade as suggested by @davinma 
`Downgrade "vue-tsc": "^2.0.4" to "vue-tsc": "^1.8.22"`

**Comment by sullyD64** [comment]
Cross referencing here since it seems to influence also `vite-plugin-checker`: https://github.com/fi3ework/vite-plugin-checker/issues/306

I think we need an upgrade path for libraries consuming `vue-tsc` v2.

**Comment by Rigo-m** [comment]
@danielroe does this require an issue tracking in the nuxt repo?

**Comment by danielroe** [comment]
Nuxt doesn't directly consume vue-tsc and I think vite-plugin-checker (which we use) is already aware.

**Comment by gygoo** [comment]
I have the same issue:
 ERROR  Cannot start nuxt:  Cannot find module 'vue-tsc/out/index'        

Stack:
"nuxt": "^3.10.3",
"vue-tsc": "^2.0.4"

 Require stack:
-  .../app-template/node_modules/.pnpm/vite-plugin-checker@0.6.4_eslint@8.57.0_stylelint@16.2.1_typescript@5.3.3_vite@5.1.4_vue-tsc@2.0.4/node_modules/vite-plugin-checker/dist/esm/checkers/vueTsc/prepareVueTsc.js

**Comment by davinma** [comment]
Downgrade `"vue-tsc": "^2.0.4"` to `"vue-tsc": "^1.8.22"`, I have tried it and worked.

**Comment by ayZagen** [comment]
this error also occurs with storybook build.

**Comment by Archetipo95** [comment]
Looks like the latest version `"vue-tsc": "^2.0.10"` is working fine with `"nuxt": "^3.11.2"`

**Comment by Mohamadhassan98** [comment]
> Looks like the latest version `"vue-tsc": "^2.0.10"` is working fine with `"nuxt": "^3.11.2"`

Not exactly. I've just upgraded nuxt and vue-tsc to latest versions (same as you said) and the error persists:

`Cannot start nuxt:  Cannot find module 'vue-tsc/out/index'`

**Comment by genu** [comment]
I can confirm. Still am issue on my end

**Comment by franklx** [comment]
I can confirm too: problem persists even with a simple `vue-tsc --noEmit` invocation

**Comment by kiketordera** [comment]
Confirmed, problem remains in `"nuxt": "^3.10.3",` and `"vue-tsc": "^2.0.16"`

**Comment by luohuiqun** [comment]
> Downgrade `"vue-tsc": "^2.0.4"` to `"vue-tsc": "^1.8.22"`, I have tried it and worked.

thanks it worked for me

**Comment by ElysaSrc** [comment]
> Looks like the latest version `"vue-tsc": "^2.0.10"` is working fine with `"nuxt": "^3.11.2"`

Issue still there.

**Comment by howbizarre** [comment]
Still here with vue-tsc version 2.0.19.
```
 ERROR  Cannot start nuxt:  Cannot find module 'vue-tsc/out/index'                                                                                                          10:21:56 ч.  
Require stack:
- \node_modules\vite-plugin-checker\dist\esm\checkers\vueTsc\prepareVueTsc.js
```

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.12.2
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  npm@10.8.0
- Builder:          -
- User Config:      runtimeConfig, modules, nitro, app, typescript, routeRules, devtools
- Runtime Modules:  @pinia/nuxt@0.5.1, @nuxt/ui@2.16.0, @nuxt/devtools@1.3.1
- Build Modules:    -
------------------------------

**Comment by prazian** [comment]
The issue is still there. Appears when upgrading `vue-tsc` from `1.8.27` to 2x.

```json
    "nuxt": "^3.11.2",
    "vue": "^3.4.27",
    "vue-router": "^4.3.2",
```

**Comment by vasilistotskas** [comment]
It appears that all Nuxt repositories configured with typescript: { typeCheck: true } and using vue-tsc version 1.8.27 or later are experiencing the same error: vue-tsc/out/index.

**Comment by allusernamestakenexceptthis** [comment]
is this related? I have issue with 3.11.2 and global components like i18T not being recognized by tsc.  it occurs only from vue-tsc 1.8.24

here is a reproduction: https://stackblitz.com/edit/github-m5xc5v-gi1rab?file=package.json

abort npm run dev, and run:

`npm run typecheck`

you'll get error:

```
error TS2339: Property 'I18nT' does not exist on type '{}'.
3     <I18nT keypath="something">asdfds</I18nT>
```

now change vue-tsc": "1.8.27" to vue-tsc": "1.8.22" and npm install, now it will work

**Comment by yanniznik** [comment]
Same issue still happening with Nuxt3 + vue-tsc 2.0.21
`Error: Cannot find module 'vue-tsc/out/index'`

**Comment by Cry0nicS** [comment]
Any updates? Still occurring with `2.0.21` and Nuxt `3.12.2`

**Comment by artemrusaleev** [comment]
Same issue still happening with Nuxt v3.12.2 and vue-tsc 2.0.21. Any updates?

**Comment by so1ve** [comment]
There is no `vue-tsc/out/index` in this codebase at all. Could you guys provide a reproduction?

**Comment by Cry0nicS** [comment]
> Same issue still happening with Nuxt v3.12.2 and vue-tsc 2.0.21. Any updates?

Downgrade vue-tsc to `1.8.27`. Seems like `2.x` doesn't play nice _yet_.

**Comment by so1ve** [comment]
https://github.com/fi3ework/vite-plugin-checker/pull/327

**Comment by howbizarre** [comment]
```typescript
export default defineNuxtConfig({
  typescript: {
    strict: true,
    typeCheck: false
  }
}
```

Disable type checking at build time and run it from the console or as script in package.json

```bash
npx nuxi typecheck
```

**Comment by ennioVisco** [comment]
> ```ts
> export default defineNuxtConfig({
>   typescript: {
>     strict: true,
>     typeCheck: false
>   }
> }
> ```
> 
> Disable type checking at build time and run it from the console or as script in package.json
> 
> ```shell
> npx nuxi typecheck
> ```

this sounds like a nuxt issue then, perhaps @danielroe can give a look at it?

**Comment by ennioVisco** [comment]
A fix is on its way, if somebody can help I'm sure it'll be appreciated: https://github.com/fi3ework/vite-plugin-checker/pull/327

**Comment by so1ve** [comment]
Closing, as https://github.com/fi3ework/vite-plugin-checker/pull/327 had been merged.

**Comment by Aietes** [comment]
The issue still occurs, it seems the require stack is still using the old vite-plugin-checker release:

```
 ERROR  Cannot start nuxt:  Cannot find module 'vue-tsc/out/index'                                                                                                                                               1:16:04 PM
Require stack:
- /.../node_modules/.pnpm/vite-plugin-checker@0.6.4_eslint@9.6.0_typescript@5.5.2_vite@5.3.2_vue-tsc@2.0.24/node_modules/vite-plugin-checker/dist/esm/checkers/vueTsc/prepareVueTsc.js

  Require stack:
  - node_modules/.pnpm/vite-plugin-checker@0.6.4_eslint@9.6.0_typescript@5.5.2_vite@5.3.2_vue-tsc@2.0.24/node_modules/vite-plugin-checker/dist/esm/checkers/vueTsc/prepareVueTsc.js
  at Module._resolveFilename (node:internal/modules/cjs/loader:1143:15)
  at Function.resolve (node:internal/modules/helpers:190:19)
```

**Comment by namhoangbes** [comment]
Yes, if you are using nuxt then you will have to wait for them to upgrade their dependencies

**Comment by namhtpyn** [comment]
Yes, if you are using nuxt then you will have to wait for them to upgrade their dependencies

**Comment by Aietes** [comment]
Ok, I hope they'll update soon. For now I'm using an override in my package.json for my nuxt  project, which makes it work in the meantime:

```
  "pnpm": {
    "overrides": {
     "vite-plugin-checker": "0.7.0"
    }
  }
```

**Comment by danielroe** [comment]
You'll get it soon, in next Nuxt patch - follow https://github.com/nuxt/nuxt/pull/27648.

**Comment by digitalniweb** [comment]
Looks like it is finally fixed
"nuxt": "^3.12.3",
"vue-tsc": "^2.0.24"

**Comment by richardevcom** [comment]
Had the same error when building my Nuxt `3.14.1592` app.
**:point_right: Fixed it by adding `typescript`: `~5.6.2` and `vue-tsc`: `2.1.10`** _(checked needed versions in `vue` and `nuxt` `package.json`)_ **as dev dependencies in my `package.json`.**
