### ISSUE TITLE
2.0.2 reports error on global properties although properly augmented

### ISSUE THREAD

**Issue by kouts** [vuejs/language-tools#3947]
We're encountering the following error after upgrading to 2.0.2
`Property '$modal' does not exist on type 'CreateComponentPublicInstance`

the property is correctly augmented as per the docs https://vuejs.org/guide/typescript/options-api.html#augmenting-global-properties
```
export {};

declare module 'vue' {
  interface ComponentCustomProperties {
    $toast: Toast;
    $modal: Modal;
  }
}
```

**Comment by kouts** [comment]
Hey @so1ve thanks for your work in this library 🙏 
Why is this issue closed? Isn't options API supported in version 2 of vue-tsc and vue language tools?

**Comment by so1ve** [comment]
Isn't this issue open?

**Comment by kouts** [comment]
Sorry @so1ve my bad 🙏 yes this issue is open, my mistake.

**Comment by davidmatter** [comment]
This works as defined [in the vue docs](https://vuejs.org/guide/typescript/options-api.html#augmenting-global-properties)
```typescript
import axios from 'axios'

declare module 'vue' {
  interface ComponentCustomProperties {
    $http: typeof axios
    $translate: (key: string) => string
  }
}
```

**Comment by douglasg14b** [comment]
@davidmatter I'm unsure why you closed this? This appears to still be an issue, I'm also experiencing this on `v2.1.4`
