### ISSUE TITLE
[vue-tsc] Generic Props gets Inferred as `unknown`

### ISSUE THREAD

**Issue by unrevised6419** [vuejs/language-tools#5592]
### Vue - Official extension or vue-tsc version

3.0.5

### VSCode version

1.102.3

### Vue version

3.5.18

### TypeScript version

5.8.0

### System Info

```shell
System:
    OS: macOS 26.0
    CPU: (8) arm64 Apple M1
    Memory: 267.22 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.15.0 - ~/.nvm/versions/node/v22.15.0/bin/node
    Yarn: 2.4.3 - ~/.nvm/versions/node/v22.15.0/bin/yarn
    npm: 11.3.0 - ~/.nvm/versions/node/v22.15.0/bin/npm
    pnpm: 9.15.9 - ~/.nvm/versions/node/v22.15.0/bin/pnpm
  Browsers:
    Brave Browser: 138.1.80.125
    Chrome: 138.0.7204.184
    Safari: 26.0
```

### package.json dependencies

```json
{
  "dependencies": {
    "vue": "^3.5.18"
  },
  "devDependencies": {
    "@tsconfig/node22": "^22.0.1",
    "@types/node": "^22.14.0",
    "@vitejs/plugin-vue": "^5.2.3",
    "@vue/tsconfig": "^0.7.0",
    "npm-run-all2": "^7.0.2",
    "typescript": "~5.8.0",
    "vite": "^6.2.4",
    "vite-plugin-vue-devtools": "^7.7.2",
    "vue-tsc": "^3.0.5"
  }
}
```

### Steps to reproduce

Having this component

**LocalScope.vue**

```vue
<script setup lang="ts" generic="T">
defineOptions({ inheritAttrs: false });
defineProps</* @vue-ignore */ T>();
</script>

<template>
	<slot v-bind="$attrs as T" />
</template>
```

And this usage

```vue
<script setup lang="ts">
import LocalScope from './LocalScope.vue';
</script>

<template>
  <LocalScope #default="{ foo, bar }" :foo="42" bar="baz">
    {{ foo }} {{ bar }}
  </LocalScope>
</template>
```

With `vue-tsc@3`, running `npx vue-tsc --build`, we have such results

```bash
src/App.vue:6:27 - error TS2339: Property 'foo' does not exist on type 'unknown'.

6   <LocalScope #default="{ foo, bar }" :foo="42" bar="baz">
                            ~~~

src/App.vue:6:32 - error TS2339: Property 'bar' does not exist on type 'unknown'.

6   <LocalScope #default="{ foo, bar }" :foo="42" bar="baz">
                                 ~~~


Found 2 errors.
```

### What is expected?

With `vue-tsc@2`, running `npx vue-tsc --build`, we no errors

### What is actually happening?

With `vue-tsc@3`, running `npx vue-tsc --build`, we have such results

```bash
src/App.vue:6:27 - error TS2339: Property 'foo' does not exist on type 'unknown'.

6   <LocalScope #default="{ foo, bar }" :foo="42" bar="baz">
                            ~~~

src/App.vue:6:32 - error TS2339: Property 'bar' does not exist on type 'unknown'.

6   <LocalScope #default="{ foo, bar }" :foo="42" bar="baz">
                                 ~~~


Found 2 errors.
```

### Link to minimal reproduction

https://github.com/unrevised6419/issue-vue-tsc-3

### Any additional comments?

This happens with Vue extension v3 also. Downgrading to v2, works fine.

https://github.com/vuejs/rfcs/discussions/505#discussioncomment-11391758

https://github.com/user-attachments/assets/b6512c78-8027-4271-9509-d4d4fa778571

**Comment by KazariEX** [comment]
It was caused by #5424. See [playground](https://www.typescriptlang.org/play/?#code/C4TwDgpgBACgThYwCWAzEAeAKgPigXigG8AoKcqAbQGkpkA7KAawhAHtUosBdALi5rcA3CQC+UAGTFRIkqEiwESNCACCAZ2rY8hUhSq0GzVhy5QAhuqjU+AmyPFSiMkiVQBXegGMUbRgGE2AFswAEZtAAowODYwdX54RBR0bQAaKHUAGzZgeOIyCgATCFRzd0zgAH5+KJi4-iwASgI8c3oQB2bnV0CQ0IiiKFQ2Nn5Q9IAjczh+ACYoUXTB4tLy4Bro2PVm-DxnBcaRAHoj-TPzi8vzgD1K1w9vXwDgsFnIzfrFJJUNLVx0rI5PJ6IolMoVapQWpbBo7VrtTrSHovWYDIYjMaTaZzBZLKArcHrKEfbYtaQHY6nK7UmlnW4kIA).

**Comment by unrevised6419** [comment]
Oh, thanks @KazariEX 

Closing in favor of https://github.com/vuejs/language-tools/issues/5159

**Comment by KazariEX** [comment]
Let's open it for now to see if there are other solutions.

**Comment by aa-ndrej** [comment]
@KazariEX sorry if I’m misunderstanding, but should https://github.com/vuejs/language-tools/pull/5424 have resolved this issue as well?  
I still see the same behavior in `vue-tsc@3.0.7`, so I just wanted to confirm.

I am running into this issue for a `LocalScope` component, see https://github.com/vuejs/rfcs/discussions/505#discussioncomment-11391758.

**Comment by KazariEX** [comment]
I mean that pr caused this issue. If we revert it, the problem it fixed will reappear.

**Comment by aa-ndrej** [comment]
Okay got it, thanks for clarifiyng!  :)
Just wanted to add that this is a regression and it worked fine in `v2`. 🙌🏼

For now my workaround (to prevent type errors) for the `LocalScope` component is the following:
```ts
<script setup generic="T" lang="ts">
defineOptions({ inheritAttrs: false })
defineProps<{ slotProps: T }>()
defineSlots<{ default?(props: T): unknown }>()
</script>

<template>
  <slot v-bind="{ ...slotProps }" />
</template>
```

Usage: `<LocalScope v-slot="{ x }" :slot-props="{ x: 'foo' }"> ...`

**Comment by unrevised6419** [comment]
A temporary solution to not change the component structure, is to make `T extends Record<string, any>` in this way the props won't be anymore inferred as `unknown`, but the props inside will be inferred as `any` (the downside)

And I suppose this is the right way to define `T` because props cannot be anything else other than an object

```vue
<script setup lang="ts" generic="T extends Record<string, any>">
defineOptions({ inheritAttrs: false });
defineProps</* @vue-ignore */ T>();
</script>

<template>
	<slot v-bind="$attrs as T" />
</template>
```

<img width="540" height="253" alt="Image" src="https://github.com/user-attachments/assets/dda61274-4568-47fe-b80c-f533eefa8a8c" />

PS: Was trying to play with internals overrides (e.g. __VLS_Props) in user land, but no success.
