### ISSUE TITLE
Build error(s) after upgrading to v3.x.x, missing __VLS_fake.d.ts

### ISSUE THREAD

**Issue by mustanggb** [vuejs/language-tools#5472]
### Vue - Official extension or vue-tsc version

v3.0.1

### VSCode version

v1.100.3

### Vue version

v3.5.17

### TypeScript version

v5.8.3

### System Info

```shell
System:
    OS: Linux 6.8 Alpine Linux
    CPU: (2) arm64 Neoverse-N1
    Memory: 3.00 GB / 7.63 GB
    Container: Yes
    Shell: Unknown - /bin/sh
Binaries:
    Node: 23.11.0 - /tmp/xfs-35cef373/node
    Yarn: 4.9.2 - /tmp/xfs-35cef373/yarn
```

### package.json dependencies

```json
{
  "name": "my-vue-app",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vue-tsc -b && vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "vue": "^3.5.17"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^6.0.0",
    "@vue/tsconfig": "^0.7.0",
    "typescript": "~5.8.3",
    "vite": "^7.0.0",
    "vue-tsc": "^3.0.1"
  },
  "packageManager": "yarn@4.9.2"
}
```

### Steps to reproduce

- yarn create vite my-vue-app --template vue-ts
- cd my-vue-app
- yarn install
- yarn up vue-tsc@latest
- yarn vue-tsc -b

### What is expected?

Succeeds without error.

### What is actually happening?

```
src/App.vue:31:22 - error TS6053: File './src/__VLS_fake.d.ts' not found.
31 /// <reference path="./__VLS_fake.d.ts" />

src/components/HelloWorld.vue:42:22 - error TS6053: File './src/components/__VLS_fake.d.ts' not found.
42 /// <reference path="./__VLS_fake.d.ts" />

Found 2 errors.
```

### Link to minimal reproduction

https://github.com/mustanggb/vue-tsc-vls-fake
https://github.com/mustanggb/vue-tsc-vls-fake/actions/runs/16028462521/job/45222469397

**Comment by KazariEX** [comment]
I followed the steps and got no errors. Please provide a minimal reproduction.

**Comment by mustanggb** [comment]
Updated with link to repo and failing action showing the errors.

**Comment by yoav-rein** [comment]
+1

Using Cursor while upgrading to "3.0.1",
got the same error for all the .vue files:
`missing __VLS_fake.d.ts`
had to downgrade back to `"vue-tsc": "2.2.10"` and now everything is working again

**Comment by johnsoncodehk** [comment]
v3 currently does not support yarn pnp, as its implementation only considers compatibility with node_modules.

**Comment by N3bby** [comment]
This also broke the build on our project (and we're using pnpm as our package manager).

I can confirm that it does work when you just use npm, but that's too big of a change for us currently.

**Comment by KazariEX** [comment]
Please provide a minimal reproduction if you have this problem with pnpm.

**Comment by Gi11i4m** [comment]
(colleague of @N3bby here)
@KazariEX Here you go, a very minimal reproduction of this error in a `Nuxt` project using `pnpm` with just 8 files including config 😃

https://github.com/Gi11i4m/vue-tsc-reproduction

We can't find the problem and there's very little to search through.

**Comment by N3bby** [comment]
@Gi11i4m and I seem to have found a fix for our issue

When we manually define vue as a dependency or hoist all dependencies using `pnpm install --shamefully-hoist` the issue disappears.

So I'm assuming there might be a problem with how vue-tsc (or libraries that it uses) interacts with the symlinks that pnpm creates in it's node_modules directory.

https://github.com/Gi11i4m/vue-tsc-reproduction/pull/1

**Comment by KazariEX** [comment]
@N3bby This is expected behavior. If you don't hoist the `vue` dependency, we have no way to resolve its path.

It's recommended to explicitly declare key dependencies such as `vue` and `vue-router`.

**Comment by N3bby** [comment]
@KazariEX I see, thanks for confirming!

So it seems like the behaviour did change with this new major version; is that correct? (as we had no issues with versions prior to 3.x)

**Comment by KazariEX** [comment]
Yes, this bug was caused by a previous bug fix.

**Comment by yoav-rein** [comment]
Have you completely dropped support for Yarn PnP?

**Comment by KazariEX** [comment]
Still exploring feasibility.

**Comment by mustanggb** [comment]
Oh exciting, looking forward to testing the next release.
