### ISSUE TITLE
Unable to infer map callback argument inside Vue template

### ISSUE THREAD

**Issue by IlyaSemenov** [vuejs/language-tools#5570]
### Vue - Official extension or vue-tsc version

3.0.4

### VSCode version

-

### Vue version

3.5.18

### TypeScript version

5.8.3

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 20.19.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.8.2 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
```

### package.json dependencies

```json
{
  "devDependencies": {
    "nuxt": "^3.18.0",
    "typescript": "^5.8.3",
    "vue-tsc": "^3.0.4"
  }
}
```

### Steps to reproduce

1. Open https://stackblitz.com/edit/nuxt-starter-vhasy428
2. Press `^C` and run: `pnpm vue-tsc --noEmit`

The file is as simple as:

```vue
<script lang="ts" setup>
import type { Component } from 'vue';

const cc: Component[] = [];
</script>

<template>
  <pre>{{ cc.map((c) => c.name) }}</pre>
</template>
```

### What is expected?

No type errors.

### What is actually happening?

```
❯ pnpm vue-tsc --noEmit
app.vue:8:19 - error TS7006: Parameter 'c' implicitly has an 'any' type.

8   <pre>{{ cc.map((c) => c.name) }}</pre>
                    ~


Found 1 error in app.vue:8
```

### Link to minimal reproduction

https://stackblitz.com/edit/nuxt-starter-vhasy428

### Any additional comments?

This is happening with any externally imported type. I chose `Component` for simplicity, it's just some type from an already installed package.

**Comment by IlyaSemenov** [comment]
Seems to be a regression introduced in 3.0.2 (it works fine in 3.0.1).

**Comment by KazariEX** [comment]
Now you need to manually set the `vueCompilerOptions.globalTypesPath` option in the stackblitz environment. We no longer generate global types into every virtual file. See #5505.

**Comment by IlyaSemenov** [comment]
Thanks for the swift heads up. That helped indeed!

**Comment by l3d00m** [comment]
Thanks for the explanation. I spent a hour debugging this a few days ago and just reverted to 3.0.1 after bisecting the update that caused this.

I'd have preferred to have this as a major (or at least minor) change. Introducing this breaking change for yarn PNP users as a 3.0.2 was kind of unexpected. I also checked the changelogs and didn't see this marked as a breaking change. I didn't expect a feature introduced in a patch version to require any action from my side.
