### ISSUE TITLE
`__VLS_globalComponents` type error

### ISSUE THREAD

**Issue by zcf0508** [vuejs/language-tools#4747]
### Vue - Official extension or vue-tsc version

2.1.2

### VSCode version

1.93.0-insider

### Vue version

3.4.21

### TypeScript version

5.5.4

### System Info

```shell
System:
    OS: macOS 14.2.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 830.18 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.13.0 - ~/.version-fox/temp/1724860800-20731/nodejs/bin/node
    npm: 8.19.3 - ~/.version-fox/temp/1724860800-20731/nodejs/bin/npm
    pnpm: 8.15.8 - ~/.version-fox/temp/1724860800-20731/nodejs/bin/pnpm
    bun: 1.1.25 - ~/.bun/bin/bun
  Browsers:
    Chrome: 128.0.6613.86
    Edge: 128.0.2739.42
    Safari: 17.2.1
```

### Steps to reproduce

In a large project, the global component type is inferred as `any`.

![image](https://github.com/user-attachments/assets/c154aeca-96a8-4f9c-bea5-303e979a0aa3)

This is the components list:

![image](https://github.com/user-attachments/assets/e3819ece-6bcd-495f-8a94-3a0275f6e2ec)

### What is expected?

The `__VLS_globalComponents` type should be inferred correctly.

![image](https://github.com/user-attachments/assets/0cd0df36-496e-410d-8295-b4ab7d1361e6)

### What is actually happening?

In a large project, the global component type is inferred as `any`.

**Comment by juanparati** [comment]
I am also facing the same issue after upgrade to 2.1.2, however it works perfect with 2.1.0.

I also I experience an higher memory consumption that in some of my linux servers overpass maximum memory heap capacity raising a NodeJS.

I tested in two different environments:

**Mac Os Sonoma 14.6.1 (Darwin Kernel Version 23.6.0 aarch64)**
vue-tsc: 2.1.2
vue: 3.4.38
vite: 5.4.2
tsc: 5.5.4

**Linux Debian 12 Bookworm (6.1.0-18-cloud-arm64)**
vue-tsc: 2.1.2
vue: 3.4.38
vite: 5.4.2
tsc: 5.5.4

**Comment by KazariEX** [comment]
Could you provide a minimal reproduction?

**Comment by juanparati** [comment]
**Steps to reproduce**
1. Upgrade to vue-tsc: 2.1.2
2. Run npm run build

Expected result:
- Component property are found successfully transpiled

Received result:
- Components properties are not found or infered (__VLS_WithComponent) . Example:
```
resources/js/Pages/Settings/Concepts/ConceptsList.vue:70:4 - error TS2339: Property 'ContentBody' does not exist on type 'Required<{} & __VLS_WithComponent<"ContentTitle", { AccordionTab: GlobalComponentConstructor<AccordionTab>; Accordion: GlobalComponentConstructor<Accordion>; ... 97 more ...; Teleport: { ...; }; } & this, "ContentTitle", "ContentTitle", "ContentTitle"> & ... 5 more ... & __VLS_WithComponent<...>>'.

70   <ContentBody ref="rfnContentBody">
      ~~~~~~~~~~~

resources/js/Pages/Settings/Concepts/ConceptsList.vue:73:8 - error TS2339: Property 'DataTable' does not exist on type 'Required<{} & __VLS_WithComponent<"ContentTitle", { AccordionTab: GlobalComponentConstructor<AccordionTab>; Accordion: GlobalComponentConstructor<Accordion>; ... 97 more ...; Teleport: { ...; }; } & this, "ContentTitle", "ContentTitle", "ContentTitle"> & ... 5 more ... & __VLS_WithComponent<...>>'.

73       <DataTable ref="datatable"
          ~~~~~~~~~
```

Workaround:
- Downgrade to vue-tsc: 2.1.0

**Environment**
Mac Os Sonoma 14.6.1 (Darwin Kernel Version 23.6.0 aarch64)
node: v20.12.2
vue-tsc: 2.1.2
vue: 3.4.38
vite: 5.4.2
tsc: 5.5.4

My projects has more than 50 components.

**Comment by davidmatter** [comment]
How have you defined your global components? Please post your declaration file here (containing just one component entry), e.g.:

```typescript
import {default as Test} from './Test.vue'

export {}

declare module 'vue' {
  export interface GlobalComponents {
    Test: typeof Test
  }
}
```

**Comment by davidmatter** [comment]
Another question: Is it possible that up until now your components were implicitly typed as 'any' and it's just starting to appear now?

**Comment by davidmatter** [comment]
Are you using `vue-facing-decorator`?

**Comment by zcf0508** [comment]
@KazariEX  [minimal reproduction](https://github.com/zcf0508/volar-component-any-repo)

**WithRefAndWithSlot.vue**

![image](https://github.com/user-attachments/assets/ca673915-d1ae-4b1b-b6f2-4667740f8667)
![image](https://github.com/user-attachments/assets/acd703df-a1fa-47d2-9535-bf40857e94ca)
![image](https://github.com/user-attachments/assets/dffbb103-4a94-404f-b160-583e25def469)

**Comment by KazariEX** [comment]
Confirmed. This is because #4644 introduces a large circular reference into the virtual code.

**Comment by zcf0508** [comment]
```
type aaa1 = {
	[K in typeof __VLS_name]: typeof __VLS_internalComponent
		& (new () => {
			$slots: typeof __VLS_slots
		})
}
type aaa2 = typeof __VLS_internalComponent extends { components: infer C } ? C : {}

type aaa3 = __VLS_GlobalComponents

type aaa4 = typeof __VLS_ctx

// This type is right
const __VLS_components1 = {} as aaa1 & aaa2 & aaa3 & aaa4;
```
![image](https://github.com/user-attachments/assets/806dcb67-929c-421f-bd46-cd5efacf6da1)

```
// This type is wrong
const __VLS_components = {
	...{} as {
				[K in typeof __VLS_name]: typeof __VLS_internalComponent
					& (new () => {
						$slots: typeof __VLS_slots
					})
			},
	...{} as NonNullable<typeof __VLS_internalComponent extends { components: infer C } ? C : {}>,
	...{} as __VLS_GlobalComponents,
	...{} as typeof __VLS_ctx,
	};
```
![image](https://github.com/user-attachments/assets/fd953492-fc47-42b1-8e50-7a8e06066675)

**Comment by zcf0508** [comment]
I need change the global type 

from `const __VLS_globalComponents = { ... {} as import('vue').GlobalComponents} ` 

to `const __VLS_globalComponents = {} as import('vue').GlobalComponents` in `__globalTypes_3.4_false.d.ts` file, 

otherwise the `__VLS_globalComponents` will always be `any`.


![image](https://github.com/user-attachments/assets/48d459d2-18cf-4063-858f-091352e82737)


![image](https://github.com/user-attachments/assets/87af0810-4dcf-4588-accb-49e442b1e86c)

**Comment by KazariEX** [comment]
You are right, this is a issue also.

**Comment by juanparati** [comment]
@davidmatter : Yes I am using the vue-facing-decorator.

**Comment by juanparati** [comment]
> Confirmed. This is because #4644 introduces a large circular reference into the virtual code.

That can explain the increase memory usage.
