### ISSUE TITLE
Object literal may only specify known properties, and 'modelModifiers' error after upgrading to 2.2.0

### ISSUE THREAD

**Issue by DamianMaslanka5** [vuejs/language-tools#5119]
### Vue - Official extension or vue-tsc version

2.2.0

### VSCode version

1.96.2

### Vue version

3.5

### TypeScript version

5.6.0

### Steps to reproduce

I see this error in tests after adding new folder to `vue3_strictTemplate` with `main.vue`:

```
<script lang="ts" setup>
import { ref } from 'vue';

const foo = ref(10);
</script>

<template>
	<select v-model.number="foo">
		<option>10</option>
		<option>20</option>
	</select>
</template>
```

### What is expected?

no error

### What is actually happening?

`"test-workspace/tsc/passedFixtures/vue3_strictTemplate/modelmodifiers/main.vue(8,17): error TS2353: Object literal may only specify known properties, and 'modelModifiers' does not exist in 
type 'ElementAttrs<SelectHTMLAttributes>'.",`
