### ISSUE TITLE
TS8013: Non-null assertions can only be used in TypeScript files.

### ISSUE THREAD

**Issue by pmiguelmartins** [vuejs/language-tools#3121]
Width version : vue-tsc 1.6.4

this code give the error : 

<template
    v-for="col in slotFilters"
    :key="col"
    #[`filter-cell-${col}`]="{ column }"
>

error TS8013: Non-null assertions can only be used in TypeScript files.

#[`filter-cell-${col}`]="{ column }"
               

Width version : vue-tsc 1.6.3

Works just fine

Any way to solve this 

Thanks

Pedro Martins

**Comment by omerbackflip** [comment]
well, i have the same problem.... any solution ?

**Comment by MarceloLuis1997** [comment]
https://github.com/microsoft/vscode/issues/181630

**Comment by qbuache** [comment]
I have that issue since I upgraded vue from 3.2.45 to 3.3.1. No error message prior to that with VSCode 1.78.1

**Comment by softy2k** [comment]
Same error with **VSCode 1.78.1**, **Volar 1.6.4** , **TypeScript Vue Plugin (Volar) 1.6.4**

**Comment by NetMango** [comment]
Same problem with Quasar which is based on Vue3:

`
        <template v-for="(htmlColumn, key) in htmlColumns" :key="key" v-slot:[computedBodyCellName(key)]="scope">
            <q-td :scope="scope" auto-width>
`

Only VSCode shows this error, but code works perfectly.

Version: 1.78.1
Commit: 6a995c4f4cc2ced6e3237749973982e751cb0bf9
Date: 2023-05-04T09:46:23.602Z
Electron: 22.5.1
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 5.15.0-71-generic
Sandboxed: Yes

**Comment by rtroost** [comment]
I don't think this is a Volar issue because our prod builds fail as well because of this error.
