### ISSUE TITLE
Getting error TS1005 after upgrading from v3.1.5

### ISSUE THREAD

**Issue by pablo-olmedo-poex** [vuejs/language-tools#5899]
### Vue - Official extension or vue-tsc version

3.2.1

### VSCode version

1.105.1

### Vue version

3.5.26

### TypeScript version

5.9.3

### System Info

```shell
System:
  OS: Windows 11 10.0.26100
  CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
  Memory: 2.57 GB / 15.69 GB
Binaries:
  Node: 22.17.1 - C:\Program Files\nodejs\node.EXE
  npm: 10.9.2 - C:\Program Files\nodejs\npm.CMD
Browsers:
  Chrome: 143.0.7499.146
  Edge: Chromium (140.0.3485.54)
  Firefox: 146.0 - C:\Program Files\Mozilla Firefox\firefox.exe
  Internet Explorer: 11.0.26100.1882
```

### package.json dependencies

```json
{
  "dependencies": {
    "awesome-phonenumber": "^7.2.0",
    "mitt": "^3.0.1",
    "quill": "^2.0.3",
    "vue-quilly": "^1.1.5"
  },
  "devDependencies": {
    "@eslint/compat": "^2.0.0",
    "@testing-library/jest-dom": "^6.9.1",
    "@testing-library/user-event": "^14.6.1",
    "@testing-library/vue": "^8.1.0",
    "@types/google.maps": "^3.58.1",
    "@types/jsdom": "^27.0.0",
    "@types/node": "^22.18.13",
    "@vitejs/plugin-vue": "^6.0.3",
    "@vue/test-utils": "^2.4.6",
    "eslint": "^9.39.2",
    "eslint-import-resolver-typescript": "^4.4.4",
    "eslint-plugin-import-x": "^4.16.1",
    "jsdom": "^27.3.0",
    "npm-run-all2": "^8.0.4",
    "prettier": "^3.7.4",
    "pug": "^3.0.3",
    "rimraf": "^6.0.1",
    "sass": "~1.97.1",
    "stylelint": "^16.26.1",
    "typescript": "^5.9.3",
    "vitest": "^4.0.16",
    "vue-tsc": "^3.2.1"
  },
  "peerDependencies": {
    "vue": "^3.5.26",
    "vue-i18n": "^11.2.7",
    "vue-router": "^4.6.4"
  }
}
```

### Steps to reproduce

I've just executed the same `npm run type-check` command I always run (`tsc --noEmit`)

### What is expected?

A successful execution

### What is actually happening?

error TS1005: ')' expected

### Any additional comments?

It worked fine until v3.1.6. After upgrading to v3.1.6, the error appeared. I had to downgrade.

I use pug for templates and ts for the script. Also using `@vue/language-plugin-pug` with the same version as `vue-tsc`

**Comment by so1ve** [comment]
Reproduction?

**Comment by johnsoncodehk** [comment]
Due to the lack of a reproduction method, this issue will be closed.
If you add a reproduction, we will reopen it. Thank you!

**Comment by pablo-olmedo-poex** [comment]
Sorry! The template is this:

```vue
<template lang="pug">
Input(
  v-bind="$attrs"
  v-model="modelValue"
  type="email"
  inputmode="email"
  autocapitalize="none"
  :name="name"
  :disabled="disabled"
  :readonly="readonly"
)
  template(v-if="hasError || hasWarning" #errorMessage)
    slot(v-if="hasError" name="errorMessage")
      | {{ errorMessage }}
    span.pe-input__warning-message(v-else :data-testid="`${name}Warning`") {{ warningMessage }}
</template>
```

The line with the alleged error is the last one:
```
span.pe-input__warning-message(v-else :data-testid="`${name}Warning`") {{ warningMessage }}
```
