### ISSUE TITLE
Error TS2322 after update vue-tsc from 1.3.8 to 1.4.4

### ISSUE THREAD

**Issue by jacob-carlborg-apoex** [vuejs/language-tools#2708]
I'm trying to update vue-tsc from 1.3.8 to 1.4.4 (the issue happens with 1.4.1 as well). When I run the type checker I get the following error:

```
src/App.vue:8:5 - error TS2322: Type 'true' is not assignable to type 'false'.

8     multiple
      ~~~~~~~~

  node_modules/vuetify/lib/components/index.d.ts:43840:9
    43840         multiple?: Multiple | undefined;
                  ~~~~~~~~
    The expected type comes from property 'multiple' which is declared here on type 'Partial<{ reverse: boolean; type: string; error: boolean; active: boolean; direction: "horizontal" | "vertical"; transition: NonNullable<string | boolean | (TransitionProps & { ...; })> | { ...; }; ... 30 more ...; openOnClear: boolean; }> & ... 4 more ... & Record<...>'


Found 1 error in src/App.vue:8
```

The relevant template looks like this:

```vue
<template>
  <v-app>
    <v-main>
      <v-select
        v-model="favorites"
        :items="states"
        label="Select"
        multiple
        hint="Pick your favorite states"
        persistent-hint
      ></v-select>
    </v-main>
  </v-app>
</template>
```

`multiple` is the only attribute it complains about. Here's an extract of the definition of the `multiple` attribute:

```typescript
& vue.VNodeProps & vue.AllowedComponentProps & vue.ComponentCustomProps & (new <T_1, ReturnObject extends boolean = false, Multiple extends boolean = false, V extends Value<T_1, ReturnObject, Multiple> = Value<T_1, ReturnObject, Multiple>>() => {
    $props: {
        items?: readonly T_1[] | undefined;
        returnObject?: ReturnObject | undefined;
        multiple?: Multiple | undefined;
        modelValue?: V | undefined;
        'onUpdate:modelValue'?: ((val: V) => void) | undefined;
    }
```

I've created a project that can reproduce the issue: https://github.com/jacob-carlborg-apoex/vuetify-select-multiple-reproduction. Run `yarn install && yarn type-check` to reproduce the issue.

**Comment by KaelWD** [comment]
Downstream issue: https://github.com/vuetifyjs/vuetify/issues/17211

Volar doesn't appear to be handling the generics correctly anyway, this is how it's supposed to work in TSX:
```js
const items = [
  { title: 'a' },
  { title: 'b' },
  { title: 'c' },
]
const Comp = (
  <VSelect items={ items } onUpdate:modelValue={ v => v } returnObject>
    {{
      item: ({ item }) => item.raw,
    }}
  </VSelect>
)
```
`item.raw` should be `{title: string}`
`v` should be `{title: string}`
add `multiple` and `v` should be `readonly {title: string}[]`

The same thing in a vue template doesn't seem to work in any recent version of volar:
```vue
<script setup lang="ts">
  const items = [
    { title: 'a' },
    { title: 'b' },
    { title: 'c' },
  ]
</script>

<template>
  <VSelect :items="items" @update:modelValue="v => v" returnObject>
    <template #item="{ item }">
      {{ item.raw }}
    </template>
  </VSelect>
</template>
```
`v` and `item` are just `any`

**Comment by johnsoncodehk** [comment]
Hi @KaelWD, the type of `VSelect` is not a legal generic component for Volar, you can change it to the following type to make it work.

```html
<script setup lang="ts">
const items = [
  { title: 'a' },
  { title: 'b' },
  { title: 'c' },
]

let VSelect: new <T_1, V, ReturnObject, Multiple>(props: {
  items?: readonly T_1[] | undefined;
  returnObject?: ReturnObject | undefined;
  multiple?: Multiple | undefined;
  modelValue?: V | undefined;
  'onUpdate:modelValue'?: ((val: V) => void) | undefined;
}) => {
  $props: typeof props;
  $slots: {
    item?: (args_0: {
      item: T_1;
      index: number;
      props: Record<string, unknown>;
    }) => any;
  }
}
</script>

<template>
  <VSelect :items="items" @update:modelValue="v => v" returnObject>
    <template #item="{ item }">
      {{ item.title }}
    </template>
  </VSelect>
</template>
```

FYI: #981, #877
