### ISSUE TITLE
Generic SFC broken from 1.8.10, 1.8.11

### ISSUE THREAD

**Issue by bradlis7** [vuejs/language-tools#3561]
I had a generic component that was working, but it isn't resolving correctly in version 1.8.10 and 1.8.11, but if I downgrade to 1.8.8, it works fine.

In this example in index.js, `item` is just resolving to `unknown`, which results in a lot of errors.

### index.vue
```JS
<CarouselSelect
  v-slot="{ item }"
  v-model="componentState.selected"
  :items="componentState.items"
  :get-key="(item) => item.id"
  class="mb-3"
>
  {{item.title}}
</CarouselSelect>
```

### CarouselSelect.vue
```JS
<script setup lang="ts" generic="T, TValue extends undefined|string|number|symbol">
const $props = defineProps<{
  items: Array<T>,
  modelValue: TValue,
  getKey: (item: T) => TValue,
}>();

defineSlots<{
  default: { item: T },
}>();
//...
</script>
```

**Comment by some-user123** [comment]
Same issue here.

You can try setting
```json
"vueCompilerOptions": {
    "strictTemplates": true
  }
```
in your `tsconfig.json` as a workaround.

**Comment by so1ve** [comment]
The version range is incorrect. Every version I tested reports this error.

**Comment by bradlis7** [comment]
Actually this might be a vue core issue. I updated my Nuxt app and all packages, and now it won't even build that file and gives the same error.

**Comment by some-user123** [comment]
> The version range is incorrect. Every version I tested reports this error.

Can't confirm that.

Reproduction: https://stackblitz.com/edit/nuxt-starter-hqnmsd?file=components%2FGenericComponent.vue,app.vue

```
❯ npm install vue-tsc@1.8.8

changed 3 packages in 5s

91 packages are looking for funding
  run `npm fund` for details

~/projects/nuxt-starter-hqnmsd 5s
❯ npm run typecheck

> typecheck
> nuxt prepare && nuxt typecheck

ℹ [nuxt] compiled plugins/server.mjs in 1245.01ms                                  21:21:32
ℹ [nuxt] compiled plugins/client.mjs in 1308.49ms                                  21:21:32
✔ Types generated in .nuxt                                                         21:21:33
ℹ [nuxt] compiled plugins/server.mjs in 2694.39ms                                  21:21:42
ℹ [nuxt] compiled plugins/client.mjs in 2946.65ms                                  21:21:42

~/projects/nuxt-starter-hqnmsd 24s
```

vs.

```
❯ npm install vue-tsc@1.8.11

changed 3 packages in 5s

91 packages are looking for funding
  run `npm fund` for details

~/projects/nuxt-starter-hqnmsd 5s
❯ npm run typecheck

> typecheck
> nuxt prepare && nuxt typecheck

ℹ [nuxt] compiled plugins/server.mjs in 1382.58ms                                  21:22:21
ℹ [nuxt] compiled plugins/client.mjs in 1473.76ms                                  21:22:21
✔ Types generated in .nuxt                                                         21:22:21
ℹ [nuxt] compiled plugins/server.mjs in 4979.01ms                                  21:22:36
ℹ [nuxt] compiled plugins/client.mjs in 5085.85ms                                  21:22:36
app.vue:5:25 - error TS18046: 'el' is of type 'unknown'.

5       :orderBy="(el) => el.toUpperCase()"
                          ~~

app.vue:8:12 - error TS18046: 'item' is of type 'unknown'.

8         {{ item.toUpperCase() }}
             ~~~~


Found 2 errors in the same file, starting at: app.vue:5


 ERROR  Command failed with exit code 2: vue-tsc --noEmit                           21:22:50

  at makeError (node_modules/nuxi/dist/chunks/index3.mjs:645:11)
  at handlePromise (node_modules/nuxi/dist/chunks/index3.mjs:1841:26)
  at async Object.run (node_modules/nuxi/dist/chunks/typecheck.mjs:94:7)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.89381a23.mjs:1674:7)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.89381a23.mjs:1665:11)
  at async runMain$1 (node_modules/nuxi/dist/shared/nuxi.89381a23.mjs:1797:7) 



 ERROR  Command failed with exit code 2: vue-tsc --noEmit                           21:22:50
```

**Comment by so1ve** [comment]
@some-user123 Thank you!

**Comment by so1ve** [comment]
Introduced in https://github.com/vuejs/language-tools/commit/cc78c5fdbc8500e20a4a715f7cd7606396c8f119
