### ISSUE TITLE
vue-tsc v2.2.0 causes Vue errors

### ISSUE THREAD

**Issue by UglyHobbitFeet** [vuejs/language-tools#5114]
### Vue - Official extension or vue-tsc version

2.2.0

### VSCode version

1.96.2

### Vue version

3.5.13

### TypeScript version

5.7.2

### System Info

```shell
N/A
```

### Steps to reproduce

Ever since upgrading from vue-tsc 2.1.10 to 2.2.0 I now get compile errors outside of my code.  You can see below multiple errors for the same line of code. Note - That line of code does not exist in my file, so it's referring to the post compiled one. Also the errors below shown 'defineCOmponent', which is not used explicitly in my code and the only appearance of that term is in the vite-env.d.ts file (shown further below)

```
src/MyFile.vue:1235:1 - error TS4082: Default export of the module has or is using private name 'DataTableHeader'.

1235 export default (await import('vue')).defineComponent({
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1236 setup() {
     ~~~~~~~~~
 ... 
1241 __typeEl: {} as __VLS_TemplateResult['rootEl'],
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1242 });
     ~~~

src/MyFile.vue:1235:1 - error TS4082: Default export of the module has or is using private name 'DataTableItem'.

1235 export default (await import('vue')).defineComponent({
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1236 setup() {
     ~~~~~~~~~
 ... 
1241 __typeEl: {} as __VLS_TemplateResult['rootEl'],
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1242 });
     ~~~

src/MyFile.vue:1235:1 - error TS4082: Default export of the module has or is using private name 'DataTableItemProps'.

1235 export default (await import('vue')).defineComponent({
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1236 setup() {
     ~~~~~~~~~
 ... 
1241 __typeEl: {} as __VLS_TemplateResult['rootEl'],
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1242 });
     ~~~

src/MyFile.vue:1235:1 - error TS4082: Default export of the module has or is using private name 'Group'.

1235 export default (await import('vue')).defineComponent({
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1236 setup() {
     ~~~~~~~~~
 ... 
1241 __typeEl: {} as __VLS_TemplateResult['rootEl'],
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1242 });
     ~~~

src/MyFile.vue:1235:1 - error TS4082: Default export of the module has or is using private name 'GroupableItem'.

1235 export default (await import('vue')).defineComponent({
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1236 setup() {
     ~~~~~~~~~
 ... 
1241 __typeEl: {} as __VLS_TemplateResult['rootEl'],
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1242 });
     ~~~

src/MyFile.vue:1235:1 - error TS4082: Default export of the module has or is using private name 'InternalItem'.

1235 export default (await import('vue')).defineComponent({
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1236 setup() {
     ~~~~~~~~~
 ... 
1241 __typeEl: {} as __VLS_TemplateResult['rootEl'],
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1242 });
     ~~~

src/MyFile.vue:1235:1 - error TS4082: Default export of the module has or is using private name 'LoaderSlotProps'.

1235 export default (await import('vue')).defineComponent({
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1236 setup() {
     ~~~~~~~~~
 ... 
1241 __typeEl: {} as __VLS_TemplateResult['rootEl'],
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1242 });
     ~~~

src/MyFile.vue:1235:1 - error TS4082: Default export of the module has or is using private name 'SelectableItem'.

1235 export default (await import('vue')).defineComponent({
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1236 setup() {
     ~~~~~~~~~
 ... 
1241 __typeEl: {} as __VLS_TemplateResult['rootEl'],
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1242 });
     ~~~

src/MyFile.vue:1235:1 - error TS7056: The inferred type of this node exceeds the maximum length the compiler will serialize. An explicit type annotation is needed.

1235 export default (await import('vue')).defineComponent({
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1236 setup() {
     ~~~~~~~~~
 ... 
1241 __typeEl: {} as __VLS_TemplateResult['rootEl'],
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1242 });
```

### What is expected?

Not to get the errors shown above upon compile

### What is actually happening?

I'm getting the errors shown above

### Any additional comments?

FWIW I'm using the standard vite-env.d.ts
```
/// <reference types="vite/client" />

declare module '*.vue' {
  import type { DefineComponent } from 'vue';
  // eslint-disable-next-line @typescript-eslint/no-explicit-any, @typescript-eslint/no-empty-object-type
  const component: DefineComponent<{}, {}, any>;
  export default component;
}
```

**Comment by RayGuo-ergou** [comment]
This has nothing to do with `DefineComponent`. To generate declaration file, `vue-tsc` has to convert vue file into ts file.

Your errors are:

> error TS4082: Default export of the module has or is using private name 'DataTableHeader'.
> error TS4082: Default export of the module has or is using private name 'Group'.
> ...

**Comment by UglyHobbitFeet** [comment]
Hi, thanks for your response!

I believe 'DataTableHeader/Group' comes directly from Vuetify source code, so I'm not sure it's anything I'm doing. I use Vuetify v3.7.6 and I followed the answer here (https://stackoverflow.com/a/75993081) to help expose the Vuetify table headers (shown below).

I created a file named: '@/types/vuetifyTableTypes.d';
```
import type { VDataTable } from 'vuetify/components'

type ReadonlyHeaders = VDataTable['$props']['headers']
type UnwrapReadonlyArray<A> = A extends Readonly<Array<infer I>> ? I : never;
export type ReadonlyDataTableHeader = UnwrapReadonlyArray<ReadonlyHeaders>;
```

Which gets called like:
```
import * as VTableTypes from '@/types/vuetifyTableTypes.d';
const headers: Ref<VTableTypes.ReadonlyDataTableHeader[]> = ref([{
    align: 'start',
    key: 'someKey',
    sortable: true,
    title: 'someTitle'
}]
```

If that was the culprit, I assume I would get an error message for every vue file that imports the VTableTypes, but I don't. So I'm not sure where to go from here.

**Comment by RayGuo-ergou** [comment]
Can you share a minimal reproduction?
I cannot reproduce with Vuetify. with

```json
    "noEmit": false,
    "outDir": "./dist",
```
I can see the declaration file correctly generated.

And I checked vuetify's type declaration file, this type is exported.

**Comment by UglyHobbitFeet** [comment]
If there is something specific you need I am happy to provide it, but I do not directly call DataTableHeader in my code, so I have no idea how to create a minimal reproduction for you to review.

I can share my package.json if that helps. I get the error when running ```pnpm tsbuild``` from command-line

```
{
  "name": "foo",
  "version": "0.0.0",
  "private": true,
  "type": "module",
  "scripts": {
    "dev": "vite --port 3111",
    "cliserve": "vite --port 3122",
    "tscbuild": "vue-tsc --noEmit && vite build",
    "build": "vite build",
    "devbuild": "vite build --mode development",
    "lint": "eslint src"
  },
  "dependencies": {
    "@mdi/font": "7.4.47",
    "@vueuse/core": "12.3.0",
    "axios": "1.7.9",
    "core-js": "3.40.0",
    "globals": "15.14.0",
    "json-editor-vue": "0.17.3",
    "moment": "2.30.1",
    "moment-timezone": "0.5.46",
    "pinia": "2.3.0",
    "roboto-fontface": "0.10.0",
    "uuid": "11.0.4",
    "vanilla-jsoneditor": "2.3.3",
    "vue": "3.5.13",
    "vue-draggable-next": "2.2.1",
    "vue-json-pretty": "2.4.0",
    "vue-router": "4.5.0",
    "vuetify": "3.7.6",
    "webfontloader": "1.6.28"
  },
  "devDependencies": {
    "@4tw/cypress-drag-drop": "2.2.5",
    "@babel/types": "7.26.3",
    "@eslint/js": "9.17.0",
    "@types/eslint__js": "8.42.3",
    "@types/node": "22.10.5",
    "@types/uuid": "10.0.0",
    "@types/webfontloader": "1.6.38",
    "@typescript-eslint/eslint-plugin": "8.19.1",
    "@vitejs/plugin-vue": "5.2.1",
    "@vue/eslint-config-typescript": "14.2.0",
    "axe-core": "4.10.2",
    "cypress": "13.17.0",
    "cypress-axe": "1.5.0",
    "eslint": "9.17.0",
    "eslint-plugin-cypress": "4.1.0",
    "eslint-plugin-vue": "9.32.0",
    "sass": "1.83.1",
    "typescript": "5.7.2",
    "typescript-eslint": "8.19.1",
    "vite": "6.0.7",
    "vite-plugin-vuetify": "2.0.4",
    "vue-tsc": "2.2.0"
  }
}
```

**Comment by KazariEX** [comment]
Type inference of `$el` and `$refs` will be disabled by default at the latest version. See #5135.
