### ISSUE TITLE
Generics with slots don't work with Vue 2.7

### ISSUE THREAD

**Issue by ferm10n** [vuejs/language-tools#3241]
It looks like a generic can be defined, but type argument doesn't appear in the slot. Instead it appears as the generic type.

Example of this working correctly with Vue 3:
https://github.com/vuejs/language-tools/blob/24968e16eb2952cec6bcd247d6d6dc1eed13bf74/packages/vue-test-workspace/vue-tsc/%232639/Bar.vue#L2-L6

Here, `Foo` has a generic `T extends { index: number }`:
https://github.com/vuejs/language-tools/blob/24968e16eb2952cec6bcd247d6d6dc1eed13bf74/packages/vue-test-workspace/vue-tsc/%232639/Foo.vue#L7

However, trying this with Vue 2.7 fails:
![image](https://github.com/vuejs/language-tools/assets/7970987/1a4bcb57-652c-4981-833d-780f4587c3a7)

## Reproduction

- starting from cloning this repo @ develop, `pnpm install --frozen-lockfile` and `pnpm build`
- from within `packages/vue-test-workspace`...
  - edit `tsconfig.json` to only target the failing test
```tsconfig
{
        // ...
	"include": [
		"vue-tsc/#2639/*"
	]
}
```
  - confirm the test is good so far with vue 3: `node ../vue-tsc/bin/vue-tsc.js --noEmit`
  - edit `packages/vue-test-workspace/package.json` to use vue 2.7 and `pnpm install`
  - running vue-tsc.js again produces this error:
```
vue-tsc/#2639/Bar.vue:4:17 - error TS2339: Property 'name' does not exist on type '{ index: number; }'.

4    <div>{{ item.name }}</div>
                  ~~~~


Found 1 error in vue-tsc/#2639/Bar.vue:4
```

## Some extra thoughts...

I'd really like to help with this project more, but it's difficult to know where to begin and it's challenging learning how all the packages in this repo work together to perform type checking.

I'm super thankful for this extension, IMO there aren't any viable alternatives for Vue 2.7 anymore. Volar seems to be the way to go, but maybe it'd be helpful to create another test package just like `vue-test-workspace`, but have it use vue 2.7 instead of vue 3. I'd imagine it'd have a subset of the tests from `vue-test-workspace`, for covering the stuff that should be possible with vue 2.7 and vue 3.

I tried creating this setup and could make a PR for it, but I could use some guidance figuring out which tests should apply to both 2 and 3. However, I wanted to know if that's even desirable for this repo before putting more effort into it. Any thoughts?

**Comment by so1ve** [comment]
Agreed. I'd like to contribute to this awesome project too but the lack of documentation made me abandon the idea

**Comment by so1ve** [comment]
Should work now
