### ISSUE TITLE
vue-tsc 3.0.2: ComponentCustomProperties augmentations dropped from component instance type

### ISSUE THREAD

**Issue by zlotnika** [vuejs/language-tools#5995]
### Environment

- vue-tsc: 3.0.2 (works on 3.0.1)
- @vue/language-core: 3.0.2 (works on 3.0.1)
- TypeScript: 5.9.3
- Vue: 3.5.28
- Nuxt: 4.3.1 (but not Nuxt-specific)
- OS: macOS

### Describe the bug

After upgrading from `vue-tsc@3.0.1` to `3.0.2`, `ComponentCustomProperties` augmentations from `declare module 'vue'` blocks are no longer merged into the component instance type in `.vue` file templates.

This causes `$route`, `$router` (from vue-router's augmentation), and all auto-imported utilities (from Nuxt's generated `imports.d.ts` augmentation) to be missing from the component instance type. The `$nuxt` property (from a separate `plugins.d.ts` augmentation using `extends`) IS present, suggesting the issue is specific to how certain `ComponentCustomProperties` augmentations are merged.

Example error:
```
app/app.vue(5,24): error TS2339: Property '$route' does not exist on type
'{ member: ...; ... 18 more ...; $nuxt: NuxtApp; }'.
```

The type includes `$nuxt: NuxtApp` (from `plugins.d.ts`) but drops all properties from:
- vue-router's `ComponentCustomProperties` augmentation (`$route`, `$router`)
- Nuxt's `imports.d.ts` `ComponentCustomProperties` augmentation (~430 auto-imported utilities)

### Reproduction

I have not been able to create a minimal standalone reproduction — the issue only manifests in a larger project (~110 `.vue` files, multiple Nuxt modules). A fresh Nuxt project with the same modules and even the same `.vue` files copied over does not reproduce it. This suggests the issue may be related to module resolution order, the number of type declarations being merged, or interaction with `unplugin-vue-router` installing a second copy of `@vue/language-core` (3.2.x alongside the 3.0.x from vue-tsc).

### Bisection

- `vue-tsc@3.0.1` (`@vue/language-core@3.0.1`, `@volar/language-core@2.4.17`): **WORKS**
- `vue-tsc@3.0.2` (`@vue/language-core@3.0.2`, `@volar/language-core@2.4.19`): **BROKEN**
- All subsequent versions (3.1.0, 3.2.x) are also broken.

### What works vs. what doesn't

| Augmentation source | Mechanism | Works? |
|---|---|---|
| `plugins.d.ts` | `interface ComponentCustomProperties extends NuxtAppInjections {}` | Yes |
| `imports.d.ts` | `interface ComponentCustomProperties { readonly navigateTo: ...; ... }` | No |
| vue-router types | `interface ComponentCustomProperties { $route: ...; $router: ...; }` | No |

### Additional context

- The generated `.d.ts` files are valid and correctly structured
- The augmentations use standard `declare module 'vue' { interface ComponentCustomProperties { ... } }` syntax
- Pinning `vue-tsc` to `3.0.1` resolves all errors
- The project has two copies of `@vue/language-core` in node_modules: one from `vue-tsc` (3.0.x) and one from `unplugin-vue-router` (3.2.x) — this dual version may be a contributing factor

**Comment by zlotnika** [comment]
Closing — after further investigation, I was unable to reproduce this reliably. My initial testing was contaminated by stale `.nuxt` generated types in a git worktree. With a clean `.nuxt` directory, vue-tsc 3.0.2 through 3.2.5 all pass correctly.

Apologies for the noise.

**Comment by zlotnika** [comment]
Reopening — the regression IS real. The Nuxt 4.4.2 upgrade (which pulls in different dependency versions) reliably triggers this in CI. I was testing against the wrong baseline earlier (main already had the upgrade reverted).

**Comment by zlotnika** [comment]
**Minimal reproduction:** https://github.com/zlotnika/nuxt-34562-repro

```bash
bun install
bun nuxi typecheck  # fails: $route not on component instance type
bun tsc --noEmit    # passes fine
```

Key finding: the bug requires a critical mass of Nuxt modules (7 modules). Removing any 1 of the last 4 makes it pass. `tsc` passes — only `vue-tsc` drops the `ComponentCustomProperties` augmentation from template types.

This suggests vue-tsc has a limit or race condition in how it merges `declare module 'vue' { interface ComponentCustomProperties }` augmentations when many `/// <reference types="..." />` directives are present.

**Comment by zlotnika** [comment]
Still hitting this. Tested today with the latest versions:

- vue 3.5.32 (released today) — still broken
- nuxt 4.4.2 — still broken
- vue-tsc 3.2.6, typescript 5.9.3 and 6.0.2

Pinning vue to 3.5.28 + nuxt to 4.3.1 remains the only workaround. This is blocking us from upgrading either package.

The reproduction at https://github.com/zlotnika/nuxt-34562-repro still applies — `bun nuxi typecheck` fails, `bun tsc --noEmit` passes.

**Comment by zlotnika** [comment]
Update: after extensive debugging, the root cause is **duplicate vue copies in node_modules**, not a vue-tsc bug.

When the root `vue` version doesn't exactly match what nuxt resolves internally, bun (and likely other package managers) installs a nested copy at `nuxt/node_modules/vue`. TypeScript then sees two separate `'vue'` module identities — augmentations declared against one copy don't apply to components resolved through the other, causing `$route`, `navigateTo`, etc. to be missing from the component instance type.

**Reproducing**: pin `vue` to any version that differs from what nuxt resolves (e.g., root `vue@3.5.28` while nuxt resolves `vue@3.5.30`). A nested `nuxt/node_modules/vue` appears and typecheck breaks.

**Fix**: deduplicate vue so there's only one copy. Either:
- Remove `vue` from your own dependencies and let nuxt provide it
- Use `overrides`/`resolutions` to force a single version  
- Delete `nuxt/node_modules/vue` after install

I confirmed this on the reproduction at https://github.com/zlotnika/nuxt-34562-repro — removing the nested `nuxt/node_modules/vue` fixes typecheck across all tested combinations (vue 3.5.28–3.5.32, nuxt 4.3.1–4.4.2).

This is arguably a nuxt packaging issue — nuxt declares `vue` as a regular dependency (`"vue": "^3.5.27"`) rather than a peer dependency, which allows package managers to install a separate copy. If it were a peer dependency, the root copy would always be used.

Closing this as not a vue-tsc issue. Sorry for the noise!

**Comment by zlotnika** [comment]
Quick follow-up on *why* two vue copies appear: nuxt declares `vue` as a regular dependency (e.g. `"vue": "^3.5.27"` in nuxt 4.3.1). If your project also lists `vue` in `dependencies` with a pinned or different version, your package manager installs a second copy at `nuxt/node_modules/vue`. TypeScript then resolves `'vue'` to different physical files depending on which `node_modules` is closest to the importing file, and augmentations declared against one copy don't apply to the other.

Fix: remove `vue` from your own `dependencies` and let nuxt provide it. The hoisted copy from nuxt is the only one you need.
