### ISSUE TITLE
vue-tsc Cannot find type definition file for 'vue/dist/__globaltypes_3.4_false.d.ts'.

### ISSUE THREAD

**Issue by Tommytrg** [vuejs/language-tools#4746]
### Vue - Official extension or vue-tsc version

2.1.2

### VSCode version

1.92.2

### Vue version

3.4.38

### TypeScript version

5.4.5

### Steps to reproduce

1. Create an empty project with `pnpm create vue@latest` using `typescript` and install dependencies.
![image](https://github.com/user-attachments/assets/01e4f377-0c03-44ca-8c0a-c82608af7638)

2. Run `pnpm type-check`  which runs `vue-tsc --build --force`
![image](https://github.com/user-attachments/assets/417023e7-fb52-40ce-a649-5e49dd1fcf8b)

### What is expected?

Get an output without errors

### What is actually happening?

The type-check script is failing with the following errors:
```
src/components/HelloWorld.vue:42:23 - error TS2688: Cannot find type definition file for 'vue/dist/__globaltypes_3.4_false.d.ts'.

42 /// <reference types="vue/dist/__globalTypes_3.4_false.d.ts" />
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/components/WelcomeItem.vue:88:23 - error TS2688: Cannot find type definition file for 'vue/dist/__globaltypes_3.4_false.d.ts'.

88 /// <reference types="vue/dist/__globalTypes_3.4_false.d.ts" />
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/components/icons/IconDocumentation.vue:8:23 - error TS2688: Cannot find type definition file for 'vue/dist/__globaltypes_3.4_false.d.ts'.

8 /// <reference types="vue/dist/__globalTypes_3.4_false.d.ts" />
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/components/icons/IconTooling.vue:20:23 - error TS2688: Cannot find type definition file for 'vue/dist/__globaltypes_3.4_false.d.ts'.

20 /// <reference types="vue/dist/__globalTypes_3.4_false.d.ts" />
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/components/icons/IconEcosystem.vue:8:23 - error TS2688: Cannot find type definition file for 'vue/dist/__globaltypes_3.4_false.d.ts'.

8 /// <reference types="vue/dist/__globalTypes_3.4_false.d.ts" />
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/components/icons/IconCommunity.vue:8:23 - error TS2688: Cannot find type definition file for 'vue/dist/__globaltypes_3.4_false.d.ts'.

8 /// <reference types="vue/dist/__globalTypes_3.4_false.d.ts" />
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/components/icons/IconSupport.vue:8:23 - error TS2688: Cannot find type definition file for 'vue/dist/__globaltypes_3.4_false.d.ts'.

8 /// <reference types="vue/dist/__globalTypes_3.4_false.d.ts" />
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/components/TheWelcome.vue:89:23 - error TS2688: Cannot find type definition file for 'vue/dist/__globaltypes_3.4_false.d.ts'.

89 /// <reference types="vue/dist/__globalTypes_3.4_false.d.ts" />
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/App.vue:48:23 - error TS2688: Cannot find type definition file for 'vue/dist/__globaltypes_3.4_false.d.ts'.

48 /// <reference types="vue/dist/__globalTypes_3.4_false.d.ts" />
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 9 errors.

 ELIFECYCLE  Command failed with exit code 2.

```

### Link to minimal reproduction

https://codesandbox.io/p/github/Tommytrg/vue-tsc-error/main?import=true

**Comment by KazariEX** [comment]
Have you enabled hybrid mode? And check if `__globalTypes_3.4_false.d.ts` exists.

**Comment by Tommytrg** [comment]
I have hybrid mode enabled and I don't see any error in vscode.

![image](https://github.com/user-attachments/assets/82f1136b-5a7c-466d-b9d0-c4b060ba3034)

I had the issue after upgrading `vue-tsc` to `2.1.2`. If I downgrade back to `2.0.29`, it works.

**Comment by Tommytrg** [comment]
That's the problem. `tsc` passes when the file name is lowercase.

![image](https://github.com/user-attachments/assets/70f9d5c6-996d-48bb-b02d-27a2590c5cdb)

![image](https://github.com/user-attachments/assets/fdf0612c-627a-4bd6-b7ee-ad3accb9c2c5)

Also, my file system is case-sensitive:

![image](https://github.com/user-attachments/assets/13a1d436-b6a3-4d36-b60a-40f33daf3854)

**Comment by KazariEX** [comment]
That's a bit weird, please use this workaround temporarily.

**Comment by codethief** [comment]
I saw the same issue on Linux / ext4 right after upgrading vue-tsc from 2.0.29 to 2.1.2 earlier. However, in the last hour or so I've switched branches a few times (-> downgrading & upgrading vue-tsc a few more times), deleted my node_modules etc. and now the error no longer shows up. Weird.

**Comment by johnsoncodehk** [comment]
Can you try using pkg.pr.newto see if #4749 fixes the problem?
```
pnpm add https://pkg.pr.new/vuejs/language-tools/vue-tsc@4749
```

**Comment by Tommytrg** [comment]
#4749 fixes the problem. Thank you for the quick reply
