### ISSUE TITLE
Ant design vue 3.2.17 template warning after update volar to 1.5.1

### ISSUE THREAD

**Issue by natuan62** [vuejs/language-tools#2691]
![image](https://user-images.githubusercontent.com/10808157/233881590-008722c0-cb4e-464d-91a6-a63bf2aed4fb.png)

```
Property 'ACard' does not exist on type 'Pick<IntrinsicElements, "div"> & { "a-modal": any; } & { "a-row": any; } & { "a-col": any; } & { "a-card": any; } & Pick<{ AppIcon: DefineComponent<{ width: (StringConstructor | NumberConstructor)[]; ... 6 more ...; disable: { ...; }; }, ... 10 more ..., { ...; }>; } & ... 8 more ... & Omit<...>, "AppIcon"> & Pick<....'. Did you mean 'a-card'?ts(2551)
```

```
Property 'ARow' does not exist on type 'Pick<IntrinsicElements, "div"> & { "a-modal": any; } & { "a-row": any; } & { "a-col": any; } & { "a-card": any; } & Pick<{ AppIcon: DefineComponent<{ width: (StringConstructor | NumberConstructor)[]; ... 6 more ...; disable: { ...; }; }, ... 10 more ..., { ...; }>; } & ... 8 more ... & Omit<...>, "AppIcon"> & Pick<....'. Did you mean 'a-row'?ts(2551)
```

```
Property 'ACol' does not exist on type 'Pick<IntrinsicElements, "div"> & { "a-modal": any; } & { "a-row": any; } & { "a-col": any; } & { "a-card": any; } & Pick<{ AppIcon: DefineComponent<{ width: (StringConstructor | NumberConstructor)[]; ... 6 more ...; disable: { ...; }; }, ... 10 more ..., { ...; }>; } & ... 8 more ... & Omit<...>, "AppIcon"> & Pick<....'. Did you mean 'a-col'?ts(2551)
```

```
Property 'AModal' does not exist on type 'Pick<IntrinsicElements, "div"> & { "a-modal": any; } & { "a-row": any; } & { "a-col": any; } & { "a-card": any; } & Pick<{ AppIcon: DefineComponent<{ width: (StringConstructor | NumberConstructor)[]; ... 6 more ...; disable: { ...; }; }, ... 10 more ..., { ...; }>; } & ... 8 more ... & Omit<...>, "AppIcon"> & Pick<....'. Did you mean 'a-modal'?ts(2551)
```

**Comment by johnsoncodehk** [comment]
Duplicate of #2688
