### ISSUE TITLE
[vue-tsc] Type error for component after updating to 1.4

### ISSUE THREAD

**Issue by augustjk** [vuejs/language-tools#2638]
Repro: https://stackblitz.com/edit/vitejs-vite-xv9dk6?file=src/App.vue

Given
```vue
<script setup lang="ts">
import { h } from 'vue';

const test = () => {
  return h('p', {}, 'test');
};
</script>

<template>
  <test />
</template>
```

Build of this fails with
```
src/App.vue:10:4 - error TS2554: Expected 0 arguments, but got 1.
10   <test />
      ~~~~
```

This used to work in 1.3.
While this can be alleviated by giving `const test` a param, I don't know if this is supposed to be erroring here in the first place.

**Comment by xue-lei** [comment]
I also have  the same problem
