### ISSUE TITLE
最新 v1.4.0 导致插槽报错

### ISSUE THREAD

**Issue by hal-wang** [vuejs/language-tools#2646]
如果降级到 1.2.0 就没有这个问题

```html
<el-table-column>
  <template #default="{ row }"> <!--Property 'row' does not exist on type 'unknown'.-->
  </template>
</el-table-column>
```

![image](https://user-images.githubusercontent.com/39717597/233531455-baf161b6-59a6-4435-b8f3-85fc21ff97d3.png)

**Comment by dungtv1291** [comment]
i think i have the same problem as you. This morning I updated the code, there are many errors

**Comment by FrankLin23** [comment]
I have the same problem in vue3 + Element Plus after i updated Volar.

**Comment by cx690** [comment]
same problem
![image](https://user-images.githubusercontent.com/37604988/233534389-26e1016b-8800-4e11-89eb-d54dcfedf75e.png)

**Comment by liujunmm** [comment]
v1.4.1 也如此

**Comment by yujw1993** [comment]
v1.4.1 同样存在

**Comment by warmthsea** [comment]
https://github.com/element-plus/element-plus/issues/12531#issuecomment-1517323337
![image](https://user-images.githubusercontent.com/45450994/233560414-5456b8b3-3d13-48db-976d-f42d3c0adbec.png)

**Comment by andy922200** [comment]
I've met the same issue after upgrading to v1.4.0 or v1.4.1.
'Downgrade to v1.2.0' can be a work around.
![截圖 2023-04-21 下午3 07 34](https://user-images.githubusercontent.com/23239750/233566296-a931c87a-e30d-47f3-bb51-58b3c5139008.png)

element-plus 2.2.5
