### ISSUE TITLE
Fallthrough attributes are recognized as errors

### ISSUE THREAD

**Issue by Under-estimate** [vuejs/language-tools#2671]
Volar plugin version `v1.4.2`
Fallthrough attributes are recognized as errors (`title` attribute in the following code):
```html
<el-button title="edit note"></el-button>
```
vscode error:
```text
Type '{ title: string; }' is not assignable to type 'IntrinsicAttributes & Partial<{ readonly type: EpPropMergeType<StringConstructor, "" | "default" | "success" | "warning" | "info" | "primary" | "danger" | "text", unknown>; ... 12 more ...; readonly autofocus: boolean; }> & Omit<...>'.
  Property 'title' does not exist on type 'IntrinsicAttributes & Partial<{ readonly type: EpPropMergeType<StringConstructor, "" | "default" | "success" | "warning" | "info" | "primary" | "danger" | "text", unknown>; ... 12 more ...; readonly autofocus: boolean; }> & Omit<...>'.ts(2322)
```
screenshot:
![image](https://user-images.githubusercontent.com/55307932/233767919-f9aa0f3d-e0e7-4ef6-bd39-0305bd8934e8.png)

**Comment by johnsoncodehk** [comment]
I can't reproduce this problem, please provide minimal reproduction.

**Comment by Under-estimate** [comment]
Here is a minimal reproduction example, run `npm install` and the error will appear in `src/App.vue`：https://github.com/Under-estimate/VueExample

**Comment by johnsoncodehk** [comment]
This seems to be expected behavior of jsx, can you remove `"jsxTemplates": true` in tsconfig?

**Comment by Under-estimate** [comment]
That solves the problem, thanks a lot!

**Comment by minikinl** [comment]
The same error:
<img width="980" alt="image" src="https://user-images.githubusercontent.com/11417330/234846240-1639ab0d-1106-4250-99ba-3bd4e8e0663b.png">

```tsx
// Inputty.tsx

{
  setup() {
    return () => <input />;
  },
}
```

***There is no `jsxTemplate` option in tsconfig.\*.json***

vue@3.2.41
vite@3.1.8


Name: **Vue Language Features (Volar)**
Id: Vue.volar
Description: Language support for Vue 3
Version: 1.6.0
Publisher: Vue
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=Vue.volar

Name: TypeScript Vue Plugin (Volar)
Id: Vue.vscode-typescript-vue-plugin
Description: Vue Plugin for TypeScript server
Version: 1.6.0
Publisher: Vue
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=Vue.vscode-typescript-vue-plugin

**Comment by minikinl** [comment]
solved by:

```
```

**Comment by coader** [comment]
> ```ts
> /**
>  * for vue components
>  * https://github.com/vuejs/language-tools/issues/1077
>  */
> declare module '@vue/runtime-core' {
>   interface AllowedComponentProps {
>     [key: string]: any;
>   }
> }
> 
> export {}
> ```

I have add this code, but still not works

**Comment by coader** [comment]
also custom directive show error after upgrade to 1.6

**Comment by romansp** [comment]
Should this be reopened? I'm still experiencing it in `.tsx` files with `vue-tsc` 1.6.0. Please see minimal repro here https://github.com/romansp/volar-repro-2671

```tsx
// App.tsx
import ButtonLink from './components/ButtonLink.vue'

const App = 
  <ButtonLink text="My Link" title="My Title" />

export default App;
```

```vue
<script setup lang="ts">
// ./components/ButtonLink.vue
defineProps<{
  text: string
}>()
</script>

<template>
  <button title="Button Title">
    {{ text }}
  </button>
</template>
```

`vue-tsc --noEmit` error
```
src/App.tsx:4:30 - error TS2322: Type '{ text: string; title: string; }' is not assignable to type 'IntrinsicAttributes & Partial<{}> & Omit<Readonly<ExtractPropTypes<__VLS_TypePropsToRuntimeProps<{ text: string; }>>> & VNodeProps & AllowedComponentProps & ComponentCustomProps, never>'.
  Property 'title' does not exist on type 'IntrinsicAttributes & Partial<{}> & Omit<Readonly<ExtractPropTypes<__VLS_TypePropsToRuntimeProps<{ text: string; }>>> & VNodeProps & AllowedComponentProps & ComponentCustomProps, never>'.

4   <ButtonLink text="My Link" title="App Title" />
                               ~~~~~


Found 1 error in src/App.tsx:4
```

```
typescript: 5.0.4
vue-tsc: 1.6.0 (takeover mode)
```

**Comment by johnsoncodehk** [comment]
@romansp thanks for the repro case, but I think it is expected behavior, you can reproduce it in regular ts code.

```ts
import { defineComponent } from 'vue';

const ButtonLink = defineComponent({
  props: { text: { type: String, required: true } }
});

const App =
  <ButtonLink text="My Link" title="My Title" />

export default App;
```

**Comment by romansp** [comment]
@johnsoncodehk Wow, okay. Odd that it used to work correctly in 1.4.0 and before. Looks like template type check became more strict?

So is there a recommended solution for this problem while still keeping type-checks for component-defined props?

**Comment by LiZhequ** [comment]
> @johnsoncodehk Wow, okay. Odd that it used to work correctly in 1.4.0 and before. Looks like template type check became more strict?
> 
> So is there a recommended solution for this problem while still keeping type-checks for component-defined props?

merge IntrinsicAttributes declaration can solve it
```ts
namespace JSX {
  export interface {
    [name: string]: any
  }
}
```

**Comment by coader** [comment]
i found if set inheritAttrs = false, will throw error, but I need this and use $attrs to bind

**Comment by coader** [comment]
now I have to use any object to pass fullthrough attribute, otherwise it can't be compiled:

const tag = (
      <NTag {...{contenteditable:'false'} as any}>
        {item.title}
      </NTag>
    )
