### ISSUE TITLE
vue-tsc 2.0.13 @vue-ignore not working above template slot

### ISSUE THREAD

**Issue by volarname** [vuejs/language-tools#4263]
### Description
Running vue-tsc on SFC with @vue-ignore above template slot not working on this example:

```
<template>
  <SomeComponent
    some-prop
  >
    <!-- @vue-ignore -->
    <template #item="{ item: itemSlot }">
      <slot
        name="item"
        :item="itemSlot as any"
      />
    </template>
  </SomeComponent>
</template>
```

This will return error, example:
```
src/components/SomeComponentvue:185:36 - error TS7022: 'itemSlot' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.
185           <template #item="{ item: itemSlot }">
```

### Expected behaviour
vue-tsc should skip this error as before, (for example it works on version 2.0.7)

### Notes
There were more issues with @vue-ignore in versions 2.0.8 - 2.0.12, these were finally fixed in 2.0.13, but this one case still persist in latest version.
