### ISSUE TITLE
Regression when using v-if / v-else within scoped templates

### ISSUE THREAD

**Issue by pfumagalli** [vuejs/language-tools#5877]
### Vue - Official extension or vue-tsc version

Working on vue-tsc 3.1.5 fails on 3.1.8

### VSCode version

N/A

### Vue version

3.5.25

### TypeScript version

5.9.3

### System Info

```shell

```

### package.json dependencies

```json

```

### Steps to reproduce

I have an auto-update dependencies job running weekly, and it caught an odd failure few weeks back when upgrading from 3.1.5 to 3.1.8 of `vue-tsc`.

I'm using Quasar, where `q-select` uses a default-scoped template with an "option"...

Minimalistic code that shows the failure:

```
<q-select ...>
  <template v-if="...condition..." #options="scope">
    ... use "scope" here, no issues
  </template>
  <template v-else #option="scope">
    ... here vue-tsc says that "scope" is non-existant ...
  </template>
</q-select>
```

The exact error message is `[TS2339] Property 'scope' does not exist on type`, you can see it in our build here:

https://github.com/juitnow/juit-vue-z/actions/runs/20152211622/job/57847309027#step:4:59

And you can see the exact code here:

https://github.com/juitnow/juit-vue-z/blob/58e1a118b8b7b4602a7acc3ab80dae66e9039308/lib/inputs/select.vue#L81-L94

### What is expected?

It's a strange regression... It used to work no problem up to 3.1.5, nothing else changed

### What is actually happening?

To be honest, no idea of the actual internals of *why* this happens

### Any additional comments?

For now, we have a workaround, applying the `v-if` / `v-else` within a sigle `<template #option="scope">` tag, but since it was working before....

**Comment by serkodev** [comment]
Thanks you! This issue has been fixed in #5844, release soon.
