### ISSUE TITLE
Offset error?

### ISSUE THREAD

**Issue by markusheiden** [vuejs/language-tools#5922]
### Vue - Official extension or vue-tsc version

3.2.1

### VSCode version

none

### Vue version

3.5.26

### TypeScript version

5.9.3

### System Info

```shell
System:
    OS: macOS 26.2
    CPU: (12) arm64 Apple M2 Max
    Memory: 3.18 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 24.8.0 - /Users/markus/.nvm/versions/node/v24.8.0/bin/node
    npm: 11.7.0 - /Users/markus/.nvm/versions/node/v24.8.0/bin/npm
    pnpm: 10.27.0 - /Users/markus/.nvm/versions/node/v24.8.0/bin/pnpm
  Browsers:
    Chrome: 143.0.7499.170
    Firefox: 146.0.1
    Safari: 26.2
```

### package.json dependencies

```json

```

### Steps to reproduce

```pug
              template(v-if="isDeveloper && !loading && job.progress")
                template(v-if="job.progress.subProgress")
                  template(v-if="job.progress.subProgress.length > 0")
 ```

### What is expected?

No error

### What is actually happening?

```
src/views/Jobs/Details/Details.vue:96:56 - error TS1005: ')' expected.

96                 template(v-if="job.progress.subProgress")
                                                          ~~
src/views/Jobs/Details/Details.vue:96:58 - error TS1002: Unterminated string literal.

96                 template(v-if="job.progress.subProgress")
                                                            
```
or if combining the condition into one line
```
src/views/Jobs/Details/Details.vue:95:95 - error TS2339: Property 'ss' does not exist on type 'CreateComponentPublicInstanceWithMixins<ToResolvedProps<{}, {}>, { isDeveloper: ComputedRef<boolean>; onConfirmRestartJob: () => Promise<void>; onConfirmStopJob: () => Promise<void>; ... 28 more ...; t: ComposerTranslation<...>; }, ... 23 more ..., {}>'.

95               template(v-if="isDeveloper && !loading && job.progress && job.progress.subProgress && job.progress.subProgress.length > 0")
                                                                                                 ~~
src/views/Jobs/Details/Details.vue:95:101 - error TS18048: '__VLS_ctx.job.progress' is possibly 'undefined'.

95               template(v-if="isDeveloper && !loading && job.progress && job.progress.subProgress && job.progress.subProgress.length > 0")
                                                                                                       ~~~~~~~~~~~~
src/views/Jobs/Details/Details.vue:95:114 - error TS2339: Property 'subProg' does not exist on type 'JobProgressModel'.

95               template(v-if="isDeveloper && !loading && job.progress && job.progress.subProgress && job.progress.subProgress.length > 0")
                                                                                                                   ~~~~~~~
```

### Any additional comments?

This worked with 3.1.5.

This is extracted from a non-SFC component that uses pug.

In other projects I have similar errors.

For me it looks like some offsets are not correct because some errors reference to partial field names like 'subProg'.
