### PR TITLE
fix(language-core): prevent eager inference of slot props from generics

### LINKED ISSUE #5228: TypeScript error with `defineSlots` and generic type since vue-tsc 2.2.4
### Vue - Official extension or vue-tsc version

2.2.4, 2.2.6

### VSCode version

1.97.2

### Vue version

3.5.13

### TypeScript version

5.8.2

### System Info

```shell
System:
    OS: macOS 15.1.1
    CPU: (8) arm64 Apple M2
    Memory: 681.22 MB / 24.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.12.0 - ~/.volta/tools/image/node/22.12.0/bin/node
    npm: 11.1.0 - ~/.volta/tools/image/npm/11.1.0/bin/npm
    bun: 1.0.4 - ~/.bun/bin/bun
  Browsers:
    Brave Browser: 133.1.75.181
    Chrome: 131.0.6778.140
    Safari: 18.1.1
```

### package.json dependencies

```json
"devDependencies":
{
    "typescript": "^5.8.2",
    "vue": "^3.5.13",
    "vue-tsc": "2.2.4"
}
```

### Steps to reproduce

```vue
<script generic="T extends string" lang="ts" setup>
interface Props
{
    slots: T[];
}
defineProps<Props>();
defineSlots<{[K in `slot:${T}`]?: () => any}>();
</script>
<template>
    <div v-for="slot of slots">
        <slot v-bind:name="`slot:${slot}`"/>
    </div>
</template>
```

When running `npx vue-tsc --noEmit`:
- With vue-tsc 2.2.2 no error is reported
- With vue-tsc 2.2.4 and vue-tsc 2.2.6 the following error is reported:

    ```
    Example.vue:11:10 - error TS2345: Argument of type '{}' is not assignable to parameter of type 'NonNullable<(Readonly<__VLS_Slots> & __VLS_Slots)[`slot:${T}`]> extends (props: infer P) => any ? P : {}'.

    11         <slot v-bind:name="`slot:${slot}`"/>
    ```

### What is expected?

No error.

### What is actually happening?

```
Example.vue:11:10 - error TS2345: Argument of type '{}' is not assignable to parameter of type 'NonNullable<(Readonly<__VLS_Slots> & __VLS_Slots)[`slot:${T}`]> extends (props: infer P) => any ? P : {}'.

11         <slot v-bind:name="`slot:${slot}`"/>
```

### Link to minimal reproduction

_No response_

### Any additional comments?

_No response_

### LINKED ISSUE #5246: ts error 2345 when using generics to define dynamic slots, after upgrade vue-tsc 2.2.2 to 2.2.4+
### Vue - Official extension or vue-tsc version

2.2.8

### VSCode version

2.2.8

### Vue version

3.5.13

### TypeScript version

5.7.3

### System Info

```shell

```

### package.json dependencies

```json

```

### Steps to reproduce

Clone repo, go to DataTable.vue, hover over title slot to see error, this didnt happen in vue-tsc 2.2.2

### What is expected?

to no show any errors on title slot, as it is defined in defineSlots

### What is actually happening?

Ts error in vue-tsc ^2.2.4:
Argument of type '{}' is not assignable to parameter of type '({ title?: (() => VNode<RendererNode, RendererElement, { [key: string]: any; }>) | undefined; } & FieldsKeys<F, T>)["title"] & (() => VNode<...>) extends (props: infer P) => any ? P : {}'

This error occurs only inside DataTable.vue, when using the component everything works fine.

### Link to minimal reproduction

https://github.com/ayrtonandino/vue-tsc-datatable-bug

### Any additional comments?

im using this generic to check for typos when i use the datatable component, for example:

```vue
<script setup lang="ts">
  import { ref } from 'vue';
  import DataTable, { type Column } from './components/DataTable.vue'

  type Item = {
    column1: string
    column2: number
  }

  const items = ref<Item[]>([])

  const columns = [
    { key: 'column2' },
    { key: 'column1' },
    { key: 'column3' },
  ] as const satisfies Column[]
</script>
```

```html
  <DataTable
    :items="items"
    :columns="columns"
  >
    <template #title>
      Table Title
    </template>

    <template #colunm3="item">
      {{ item.index }}
    </template>
  </DataTable>
```
Return this error: Property 'colunm3' does not exist on type '__VLS_Slots'.ts-plugin(2339).

### PR DESCRIPTION
**Pull request by KazariEX**
fix #5228, fix #5246

### CODE REVIEW

**Comment by targetlucked69** [comment]
is this fix available in 2.2.8 already? thanks!

**Comment by KazariEX** [comment]
@targetlucked69 It was included in the `v3.0.0-alpha.0`.

**Comment by shossk** [comment]
@KazariEX When will v3.0.0 be released? I'm having trouble.

**Comment by KazariEX** [comment]
@shossk see #5261.

**Comment by sandros94** [comment]
@KazariEX sorry for the ping, I've been following this for quite a bit hoping to find a fix myself but I'm getting more and more lost.

Over Nuxt UI I'm trying to fix a type utility to dynamically type slot names. The developer passes an array to the component, where each item may have its own slot name and depending on the component it might also have one or multiple suffix to that slot name (eg: `<name>`, `<name>-leading`, `<name>-trailing`). In runtime this named slot will only be bound to that particular item in the input array, so it is only a matter of typing everything correctly.

I tried to mimic as much as possible the implementation from this PR, but I'm still getting error:
```
../src/runtime/components/Test.vue:40:8 - error TS2345: Argument of type '{ item: T; index: number; }' is not assignable to parameter of type 'NonNullable<(Readonly<{ item: (props: { item: T; index: number; }) => any; 'item-trailing': (props: { item: T; index: number; }) => any; } & DynamicSlots<T, "trailing", { index: number; }>> & { ...; } & DynamicSlots<...>)["item" | ... 2 more ... | `${T["slot"] & string}-trailing`]> extends (props: infer P) => any ? P : {}'.

../src/runtime/components/Test.vue:45:8 - error TS2345: Argument of type '{ item: T; index: number; }' is not assignable to parameter of type 'NonNullable<(Readonly<{ item: (props: { item: T; index: number; }) => any; 'item-trailing': (props: { item: T; index: number; }) => any; } & DynamicSlots<T, "trailing", { index: number; }>> & { ...; } & DynamicSlots<...>)["item" | ... 2 more ... | `${T["slot"] & string}-trailing`]> extends (props: infer P) => any ? P : {}'.
```

The following is the smallest reproduction I was able to make (I'm interested in the `DynamicSlots` utility type):

```vue
<script lang="ts">
interface TestItem {
  label: string
  slot?: string
}

interface TestProps<T extends TestItem> {
  items: T[]
}

type DynamicSlots<
  T extends { slot?: string },
  S extends string | undefined = undefined,
  D extends object = {}
> = {
  [K in (T['slot'] & string | `${T['slot'] & string}-${S & string}`)]: (props: {
    item: Extract<T, { slot: S extends undefined
      ? K
      : K extends `${infer Base}-${S & string}`
        ? Base
        : K }>
  } & D) => any
}

type TestSlots<T extends TestItem> = {
  'item': (props: { item: T, index: number }) => any
  'item-trailing': (props: { item: T, index: number }) => any
} & DynamicSlots<T, 'trailing', { index: number }>

</script>

<script setup lang="ts" generic="T extends TestItem">
defineProps<TestProps<T>>()
defineSlots<TestSlots<T>>()
</script>

<template>
  <div v-for="(item, index) of $props.items" :key="index">
    <span>
      <slot
        :name="((item.slot ? item.slot : 'item') as keyof TestSlots<T>)"
        :item="item"
        :index="index"
      />
      <slot
        :name="((item.slot ? `${item.slot}-trailing` : 'item-trailing') as keyof TestSlots<T>)"
        :item="item"
        :index="index"
      />
    </span>
  </div>
</template>
```

**Comment by KazariEX** [comment]
@sandros94 How did you solve this problem?

**Comment by sandros94** [comment]
> @sandros94 How did you solve this problem?

I'm not sure I have resolved it tbh, but I realized that I was getting those typecheck errors only in the local docs and not playgrounds, so there might be an issue on our end.

And considering it is the first time I debug vue-tsc I tend to think about me doing something wrong. If you have some free time I would gladly take any advice and much appreciated if you could take a look at that example I've made 🙏

**Comment by KazariEX** [comment]
This is the final code that caused the problem:

image

You can install the Volar Labs extension and check the virtual code of this sfc.

**Comment by sandros94** [comment]
> This is the final code that caused the problem:
> 
> [...]
> 
> You can install the Volar Labs extension and check the virtual code of this sfc.

you mean [this extension](https://marketplace.visualstudio.com/items?itemName=johnsoncodehk.volarjs-labs)?

Could I ask a link to docs or a bit of guidance on how to correctly debug it and access its virtual code?

> Even without going through our normalize function, this slot still cannot be directly called:

You mean that it is not possible to pick that specific slot? Sorry, I might be missing the meaning of some terminology like "calling slots"
