### ISSUE TITLE
Propagating slots fails with pug if using "special" comment

### ISSUE THREAD

**Issue by markusheiden** [vuejs/language-tools#5921]
### Vue - Official extension or vue-tsc version

3.2.1

### VSCode version

none

### Vue version

3.5.26

### TypeScript version

5.9.3

### System Info

```shell
System:
    OS: macOS 26.2
    CPU: (12) arm64 Apple M2 Max
    Memory: 3.18 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 24.8.0 - /Users/markus/.nvm/versions/node/v24.8.0/bin/node
    npm: 11.7.0 - /Users/markus/.nvm/versions/node/v24.8.0/bin/npm
    pnpm: 10.27.0 - /Users/markus/.nvm/versions/node/v24.8.0/bin/pnpm
  Browsers:
    Chrome: 143.0.7499.170
    Firefox: 146.0.1
    Safari: 26.2
```

### package.json dependencies

```json
"devDependencies": {
    "@testing-library/dom": "10.4.1",
    "@testing-library/jest-dom": "6.9.1",
    "@testing-library/user-event": "14.6.1",
    "@testing-library/vue": "8.1.0",
    "@types/node": "24.10.4",
    "@vitejs/plugin-vue": "6.0.3",
    "@vitest/ui": "4.0.16",
    "@vue/test-utils": "2.4.6",
    "@vueuse/core": "14.1.0",
    "chokidar-cli": "3.0.0",
    "jsdom": "27.4.0",
    "pinia": "3.0.4",
    "pug": "3.0.3",
    "sass": "1.97.1",
    "typescript": "5.9.3",
    "vite": "7.3.0",
    "vite-plugin-dts": "4.5.4",
    "vite-plugin-vuetify": "2.1.2",
    "vitest": "4.0.16",
    "vue": "3.5.26",
    "vue-component-type-helpers": "3.2.1",
    "vue-i18n": "11.2.8",
    "vue-router": "4.6.4",
    "vue-tsc": "3.2.1",
    "vuetify": "3.11.6"
  }
```

### Steps to reproduce

```vue
<script setup lang="ts">
import { useSlots } from 'vue';
const slots = useSlots();
</script>
<template lang="pug">
v-dialog
  //- Automatically passing slots does NOT work. We need to manually delegate all slots here.
  template(v-for="(_, slotName) in slots", #[slotName]="slotProps")
    slot(v-bind="slotProps", :name="slotName")
</template>
```

### What is expected?

Slots are passed through like with vue-tsc 3.1

### What is actually happening?

Bug.vue(5,21): error TS2339: Property 'slotName' does not exist on type '{ slots: Readonly<InternalSlots>; $: ComponentInternalInstance; $data: {}; $props: {}; $attrs: Data; $refs: Data; $slots: Readonly<...>; ... 20 more ...; $tm<Key extends string, DefinedLocaleMessage extends RemovedIndexResources<DefineLocaleMessage> = RemoveIndexSignature<...>, Keys = IsEmptyObject<...> extends fals...'.
Bug.vue(5,22): error TS2339: Property 'slotName' does not exist on type '{ slots: Readonly<InternalSlots>; $: ComponentInternalInstance; $data: {}; $props: {}; $attrs: Data; $refs: Data; $slots: Readonly<...>; ... 20 more ...; $tm<Key extends string, DefinedLocaleMessage extends RemovedIndexResources<DefineLocaleMessage> = RemoveIndexSignature<...>, Keys = IsEmptyObject<...> extends fals...'.

### Link to minimal reproduction

See above.

### Any additional comments?

Worked with vue-tsc 3.1.5.

Removing the comment makes it compile. Something special in the comment makes this fail because using just `...` as comment does not make this fail. Using just the second sentence as comment leads to another error.

I have another component using slot propagation that doesn't work without a comment (with another text) directly in front of it.

Or may this be a problem of the pug integration being incompatible with vue-tsc 3.2+?
