### ISSUE TITLE
Error when upgrading to 2.0.0

### ISSUE THREAD

**Issue by Stanzilla** [vuejs/language-tools#3919]
```
> vue-tsc --noEmit && vite build && electron-builder "--publish=never"

node:internal/modules/cjs/loader:1147
  throw err;
  ^

Error: Cannot find module '../index.js'
Require stack:
- /home/runner/work/WeakAuras-Companion/WeakAuras-Companion/node_modules/vue-tsc/bin/vue-tsc.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/home/runner/work/WeakAuras-Companion/WeakAuras-Companion/node_modules/vue-tsc/bin/vue-tsc.js:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:[10](https://github.com/WeakAuras/WeakAuras-Companion/actions/runs/8117655749/job/22190328028?pr=2377#step:8:11))
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/WeakAuras-Companion/WeakAuras-Companion/node_modules/vue-tsc/bin/vue-tsc.js'
  ]
}

Node.js v20.[11](https://github.com/WeakAuras/WeakAuras-Companion/actions/runs/8117655749/job/22190328028?pr=2377#step:8:12).1
 ELIFECYCLE  Command failed with exit code 1.
 ```

See https://github.com/WeakAuras/WeakAuras-Companion/pull/2377

**Comment by toniengelhardt** [comment]
Same

**Comment by ferreira-tb** [comment]
Same here.

`vue-tsc.js` requires `../index.js`, but no such file exists. Maybe it was a mistake when publishing the new version?
